objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Artera_Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Job Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Assignment in Progress</fullName>
                </value>
                <value>
                    <fullName>Dispatched</fullName>
                </value>
                <value>
                    <fullName>Dispatched - Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Pending Supervisor Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Admin Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Billing Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Payroll Approval</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Company__c</field>
                <operation>equals</operation>
                <value>025</value>
            </filterItems>
            <filterItems>
                <field>Account.Status__c</field>
                <operation>equals</operation>
                <value>A</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Hydro_X_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project__c.Status__c</field>
                <operation>equals</operation>
                <value>A</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs1</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Artera_Job_Allocation__c.object
<CustomObject>
    <label>Job Assignment</label>
    <nameField>
        <displayFormat>JAN-{0000}</displayFormat>
        <label>Job Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unassigned</fullName>
                    <default>true</default>
                    <label>Unassigned</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                    <isActive>false</isActive>
                    <label>Declined</label>
                </value>
                <value>
                    <fullName>Dispatch</fullName>
                    <isActive>false</isActive>
                    <label>Dispatch</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>Job__r.Project__r.Project_Id__c</formula>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <formula>Artera_Resource__r.Employee_ID__c</formula>
        <label>Employee ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Half_Day_Leave__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Half Day Leave</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Artera_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Artera_Resource__c.Worker_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Artera_Resource__c</referenceTo>
        <relationshipLabel>Job Assignments</relationshipLabel>
        <relationshipName>Hydro_X_Job_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Artera_Resource__c.object
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <externalId>true</externalId>
        <label>Employee ID</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

objects/Leave__c.object
<CustomObject>
    <label>Leave</label>
    <nameField>
        <displayFormat>L-{000000000}</displayFormat>
        <label>Leave Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leaves</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BEREAV</fullName>
                </value>
                <value>
                    <fullName>HOLWRK</fullName>
                </value>
                <value>
                    <fullName>JURY</fullName>
                </value>
                <value>
                    <fullName>OTHER</fullName>
                </value>
                <value>
                    <fullName>PERSONAL</fullName>
                </value>
                <value>
                    <fullName>PTO</fullName>
                </value>
                <value>
                    <fullName>SICK</fullName>
                </value>
                <value>
                    <fullName>SICK UNPAID</fullName>
                </value>
                <value>
                    <fullName>VBP</fullName>
                </value>
                <value>
                    <fullName>ABSENT</fullName>
                    <isActive>false</isActive>
                    <label>ABSENT</label>
                </value>
                <value>
                    <fullName>Bad Weather</fullName>
                    <isActive>false</isActive>
                    <label>Bad Weather</label>
                </value>
                <value>
                    <fullName>HOLIDAY</fullName>
                    <isActive>false</isActive>
                    <label>HOLIDAY</label>
                </value>
                <value>
                    <fullName>HRLY VAC</fullName>
                    <isActive>false</isActive>
                    <label>HRLY VAC</label>
                </value>
                <value>
                    <fullName>NO SHOW</fullName>
                    <isActive>false</isActive>
                    <label>NO SHOW</label>
                </value>
                <value>
                    <fullName>OFF DUTY</fullName>
                    <isActive>false</isActive>
                    <label>OFF DUTY</label>
                </value>
                <value>
                    <fullName>VACATION</fullName>
                    <isActive>false</isActive>
                    <label>VACATION</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Leave cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Half_Day_Leave__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Half Day Leave</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Leave_End_Date__c</fullName>
        <label>Leave End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Artera_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Artera Resource</label>
        <referenceTo>Artera_Resource__c</referenceTo>
        <relationshipLabel>Leaves</relationshipLabel>
        <relationshipName>Leaves</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Leave_Start_Time__c</fullName>
        <label>Leave Start Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Leave_Start_date__c</fullName>
        <label>Leave Start date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reason_for_leave_rejection__c</fullName>
        <label>Reason for Leave Rejection</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company_Id__c</fullName>
        <label>Company Id</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>025</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/createJobAssignmentTest.cls
@isTest
public class createJobAssignmentTest {
  /*  @isTest 
    static void addJobTest(){
        // List <Artera_Job_Allocation__c> jobAssignment = new List<Artera_Job_Allocation__c>();
       
       Account acc = new Account();
        acc.Name  = 'Test Account 04';
        insert acc;
        
        List <Artera_Job__c> job = new List<Artera_Job__c>();
        Artera_Resource__c r = new Artera_Resource__c();
        r.Name = 'Tim';
        r.Employee_ID__c = 'E1S50X2BA23';
        r.Email__c= 'ritisha.chavan@artera.com';
        insert r;
        
        List <Leave__c> leaveList = new List<Leave__c>();
        Artera_Resource__c res = new Artera_Resource__c();
        res.Name = 'Elmore, Timothy L';
        res.Employee_ID__c = 'PJE9DX5R7I';
        res.Email__c= 'telmore@hydroexcavators.com';
        insert res;

        Leave__c l = new Leave__c();
        DateTime dt = DateTime.now();
         Time endtime =dt.timeGmt();
        l.Status__c = 'Rejected';
        l.Reason_for_leave_rejection__c= 'Bereave';
        l.Half_Day_Leave__c = true;
        l.Leave_Start_date__c = Date.newInstance(2022, 05, 1);
        l.Leave_End_Date__c = Date.newInstance(2022, 05, 2);
        l.Reason__c = 'HOLWRK';
        l.Half_Day_Leave__c=True;
        l.Leave_Start_Time__c= endtime;
        
        l.Artera_Resource__c = r.Id;
        Insert l;
        
        List <Artera_Job__c> newJob = new List<Artera_Job__c>();
        
        Project__c project = new Project__c();
        project.Name = 'Test Project';
        project.Company_Id__c = '025';
        project.Account__c = acc.Id;
        project.Status__c = 'A';
        insert project;
        
        Test.startTest();
        leaveList.add(l); 
        System.debug('leaveList' + leaveList);
        createJobAssignment.addJob(leaveList);
        Test.stopTest();
    }*/
    
    @isTest static void addJobTest1(){
        List <Leave__c> leaveList1 = new List<Leave__c>();
        Artera_Resource__c r = new Artera_Resource__c();
        r.Name = 'Tom';
        r.Employee_ID__c = 'E1S50X2BA23';
        r.Email__c= 'ritisha.chavan@artera.com';
        insert r;
        
        Leave__c l = new Leave__c();
        l.Status__c = 'Rejected';
        l.Leave_Start_date__c = Date.newInstance(2022, 05, 1);
        l.Leave_End_Date__c = Date.newInstance(2022, 05, 2);
        l.Reason__c = 'HOLWRK';
        l.Reason_for_leave_rejection__c = 'No leaves remaining';
        l.Artera_Resource__c = r.Id;
        
        Test.startTest();
        leaveList1.add(l);
        System.debug('leaveList1' + leaveList1);
        createJobAssignment.addJob(leaveList1);
        Test.stopTest();
    }  
     @isTest
     static  void testIncrement() {
         Test.startTest();
        createJobAssignment.justIncrement();
 		Test.stopTest();
     }
}