objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Artera_Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Job Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Assignment in Progress</fullName>
                </value>
                <value>
                    <fullName>Dispatched</fullName>
                </value>
                <value>
                    <fullName>Dispatched - Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Pending Supervisor Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Admin Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Billing Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Payroll Approval</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Company__c</field>
                <operation>equals</operation>
                <value>025</value>
            </filterItems>
            <filterItems>
                <field>Account.Status__c</field>
                <operation>equals</operation>
                <value>A</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Hydro_X_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Date__c</fullName>
        <label>Job Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Job_Location__c</fullName>
        <label>Job Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Artera_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Area</label>
        <referenceTo>Artera_Region__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Hydro_X_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Artera_Job_Allocation__c.object
<CustomObject>
    <label>Job Assignment</label>
    <nameField>
        <displayFormat>JAN-{0000}</displayFormat>
        <label>Job Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Artera_Job__c</referenceTo>
        <relationshipName>Job_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unassigned</fullName>
                    <default>true</default>
                    <label>Unassigned</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                    <isActive>false</isActive>
                    <label>Declined</label>
                </value>
                <value>
                    <fullName>Dispatch</fullName>
                    <isActive>false</isActive>
                    <label>Dispatch</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Per_Diem__c</fullName>
        <label>Per Diem</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lunch_Time__c</fullName>
        <defaultValue>30</defaultValue>
        <label>Lunch Time (in mins)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <formula>Artera_Resource__r.Employee_ID__c</formula>
        <label>Employee ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Artera_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Artera_Resource__c.Worker_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Artera_Resource__c</referenceTo>
        <relationshipLabel>Job Assignments</relationshipLabel>
        <relationshipName>Hydro_X_Job_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Artera_Region__c.object
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Artera Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Region</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <scale>8</scale>
        <type>Location</type>
    </fields>
</CustomObject>

objects/Artera_Resource__c.object
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <externalId>true</externalId>
        <label>Employee ID</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Artera_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Artera Region</label>
        <referenceTo>Artera_Region__c</referenceTo>
        <relationshipName>Artera_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Hydro_X_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Job_Ticket__c.object
<CustomObject>
    <label>Job Ticket</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Job Ticket Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Job1__c</fullName>
        <label>Job</label>
        <referenceTo>Artera_Job__c</referenceTo>
        <relationshipLabel>Job Tickets</relationshipLabel>
        <relationshipName>Job_Tickets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#FF0000</color>
                    <label>Cancelled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Time</type>
    </fields>
</CustomObject>

objects/Job_Ticket_Detail__c.object
<CustomObject>
    <label>Job Ticket Detail</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Job Ticket Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Tickets Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Artera_Job__c</referenceTo>
        <relationshipLabel>Job Tickets Detail</relationshipLabel>
        <relationshipName>Job_Tickets_Detail</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job_Date__c</fullName>
        <formula>Job_Ticket__r.Job1__r.Job_Date__c</formula>
        <label>Job Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <formula>LEFT(Job_Ticket__r.Location__c,30)</formula>
        <label>Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Ticket__c</fullName>
        <label>Job Ticket</label>
        <referenceTo>Job_Ticket__c</referenceTo>
        <relationshipLabel>Job Tickets Detail</relationshipLabel>
        <relationshipName>Job_Tickets_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

classes/dispatcher2CtrlerTest.cls
@isTest
public class dispatcher2CtrlerTest {

    @isTest
    public static void testMethod1(){
        Account acc =new Account();
        acc.Name = 'Test Account';
        insert acc;
        
        
        
        Artera_Job__c job1 = new Artera_Job__c();
        Artera_Region__c reg = new Artera_Region__c(name = 'FL - Tampa');
        String regionName = 'FL - Tampa';
        List<String> regList = new List<String>();
        regList.add(regionName);
        //job1.Name = 'Testing';
        job1.Status__c ='Dispatched - Acknowledged';
        job1.Job_Date__c = System.today();
        job1.account__c = acc.Id;
        job1.Job_Location__c = 'test location';
        insert reg;
        insert job1;
        
        
        Artera_Job__c job2 = new Artera_Job__c();
        //job2.Name = 'f tFilling';
        job2.Status__c ='Dispatched';
        job2.Job_Date__c = System.today();
        job2.account__c = acc.Id;
        job2.Job_Location__c = 'test location';
        insert job2;
        list<id> jobids = new list<id>();
        jobids.add(job2.Id);
        jobids.add(job1.Id);
        
        Artera_Resource__c resource = new Artera_Resource__c();
        resource.Name = 'test operator';
        resource.Email__c = 'aamir@bugendaitech.com';
        resource.Salesforce_User__c = userinfo.getUserId();
        resource.Employee_ID__c = 'test emp';
        insert resource; 
        
        Artera_Job_Allocation__c alloc = new Artera_Job_Allocation__c();
        alloc.Artera_Resource__c = resource.Id;
        alloc.Job__c = job1.Id ;
        alloc.Start_Time__c = null; 
        alloc.End_Time__c = null;
        alloc.Lunch_Time__c =20;
        alloc.Per_Diem__c = 'Yes';
        insert alloc;
        
        
        Job_Ticket__c jobticket = new Job_Ticket__c();
        jobticket.Job1__c = job1.id;
        jobticket.Location__c='Atlanta';
        insert jobticket;
        
        Job_Ticket_Detail__c jobticketdetails = new Job_Ticket_Detail__c();
        jobticketdetails.Job_Ticket__c = jobticket.Id;
        insert jobticketdetails;
        
        Test.startTest();
        dispatcher2ctrler.updateAssignmentData(alloc);
        dispatcher2ctrler.updateTicketData(jobticket);
        dispatcher2ctrler.deleteAssigns(alloc.id);
        //dispatcher2ctrler.getSearchList('All', '');
        //dispatcher2ctrler.getSearchList('My', '');
        dispatcher2ctrler.getAllJobAllocationsForDis('All', true);
        dispatcher2ctrler.getAllJobAllocationsForDisRefreshData('All', true);
        dispatcher2ctrler.getSearchListByFilter('My','',null,regList,true);
        dispatcher2ctrler.getSearchListByFilter('All','',null,regList,true);
        Test.stopTest();
    }
    @isTest
    static void JobAllocationWrapperTest()
    {
         Account acc =new Account();
        acc.Name = 'Test Account';
        insert acc;
        
        
        Artera_Job__c job1 = new Artera_Job__c();
        Artera_Region__c reg = new Artera_Region__c(name = 'FL - Tampa');
        String regionName = 'FL - Tampa';
        List<String> regList = new List<String>();
        regList.add(regionName);
        //job1.Name = 'Testing';
        job1.Status__c ='Dispatched - Acknowledged';
        job1.Job_Date__c = System.today();
        job1.account__c = acc.Id;
        job1.Job_Location__c = 'test location';
        insert reg;
        insert job1;
        
        Artera_Resource__c resource = new Artera_Resource__c();
        resource.Name = 'test operator';
        resource.Email__c = 'aamir@bugendaitech.com';
        resource.Salesforce_User__c = userinfo.getUserId();
        resource.Employee_ID__c = 'test emp';
        insert resource; 
        
        Artera_Job_Allocation__c alloc = new Artera_Job_Allocation__c();
        alloc.Artera_Resource__c = resource.Id;
        alloc.Job__c = job1.Id ;
        alloc.Start_Time__c = null; 
        alloc.End_Time__c = null;
        alloc.Lunch_Time__c =20;
        alloc.Per_Diem__c = 'Yes';
        insert alloc;
        
        // Parameters 
        String URLs = '/' +alloc.Id ;
        string AllocationName =alloc.Name;
        string ResNameEx = 'John'; 
        
        string ResEmpId = '12323453123';
        string JobAllocStatus = 'Assigned';
        //dispatcher2ctrler.JobAllocWrapper(alloc.Id , AllocationName,alloc.Id ,ResNameEx,ResEmpId,JobAllocStatus);

    }
     @isTest
     static  void testIncrement() {
         Test.startTest();
        dispatcher2Ctrler.justIncrement();
 		Test.stopTest();
     }
}