objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Artera_Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Job Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Assignment in Progress</fullName>
                </value>
                <value>
                    <fullName>Dispatched</fullName>
                </value>
                <value>
                    <fullName>Dispatched - Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Pending Supervisor Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Admin Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Billing Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Payroll Approval</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Company__c</field>
                <operation>equals</operation>
                <value>025</value>
            </filterItems>
            <filterItems>
                <field>Account.Status__c</field>
                <operation>equals</operation>
                <value>A</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Hydro_X_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project__c.Status__c</field>
                <operation>equals</operation>
                <value>A</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Date__c</fullName>
        <label>Job Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <label>Job Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Off Duty</fullName>
                </value>
                <value>
                    <fullName>Non- Billable</fullName>
                </value>
                <value>
                    <fullName>Leave</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <label>Internal</label>
    </recordTypes>
</CustomObject>

objects/Artera_Job_Allocation__c.object
<CustomObject>
    <label>Job Assignment</label>
    <nameField>
        <displayFormat>JAN-{0000}</displayFormat>
        <label>Job Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Artera_Job__c</referenceTo>
        <relationshipName>Job_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assignment</fullName>
                </value>
                <value>
                    <fullName>Leave</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Non- Billable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unassigned</fullName>
                    <default>true</default>
                    <label>Unassigned</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                    <isActive>false</isActive>
                    <label>Declined</label>
                </value>
                <value>
                    <fullName>Dispatch</fullName>
                    <isActive>false</isActive>
                    <label>Dispatch</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Paycode__c</fullName>
        <label>Pay Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ABSENT</fullName>
                </value>
                <value>
                    <fullName>Bad Weather</fullName>
                    <label>BAD WEATHER</label>
                </value>
                <value>
                    <fullName>BEREAV</fullName>
                </value>
                <value>
                    <fullName>HOLWRK</fullName>
                </value>
                <value>
                    <fullName>JURY</fullName>
                </value>
                <value>
                    <fullName>NO SHOW</fullName>
                </value>
                <value>
                    <fullName>OFF DUTY</fullName>
                </value>
                <value>
                    <fullName>OTHER</fullName>
                </value>
                <value>
                    <fullName>PERSONAL</fullName>
                </value>
                <value>
                    <fullName>PTO</fullName>
                </value>
                <value>
                    <fullName>SICK</fullName>
                </value>
                <value>
                    <fullName>SICK UNPAID</fullName>
                </value>
                <value>
                    <fullName>VBP</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                    <default>true</default>
                    <label>N/A</label>
                </value>
                <value>
                    <fullName>HOLIDAY</fullName>
                    <isActive>false</isActive>
                    <label>HOLIDAY</label>
                </value>
                <value>
                    <fullName>HRLY VAC</fullName>
                    <isActive>false</isActive>
                    <label>HRLY VAC</label>
                </value>
                <value>
                    <fullName>VACATION</fullName>
                    <isActive>false</isActive>
                    <label>VACATION</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>Job__r.Project__r.Project_Id__c</formula>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Half_Day_Leave__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Half Day Leave</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Artera_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Artera_Resource__c.Worker_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Artera_Resource__c</referenceTo>
        <relationshipLabel>Job Assignments</relationshipLabel>
        <relationshipName>Hydro_X_Job_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Leave__c.object
<CustomObject>
    <label>Leave</label>
    <nameField>
        <displayFormat>L-{000000000}</displayFormat>
        <label>Leave Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leaves</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Leave cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Half_Day_Leave__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Half Day Leave</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Artera_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Artera Resource</label>
        <referenceTo>Artera_Resource__c</referenceTo>
        <relationshipLabel>Leaves</relationshipLabel>
        <relationshipName>Leaves</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Leave_Start_Time__c</fullName>
        <label>Leave Start Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Leave_Start_date__c</fullName>
        <label>Leave Start date</label>
        <type>Date</type>
    </fields>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

classes/createJobAssignment.cls
public class createJobAssignment {   
    public static void addJob(List <Leave__c> leaveLists){
        Integer iDays;
        List<Artera_Job_Allocation__c> jobs = new List<Artera_Job_Allocation__c>();
        List<Artera_Job__c> newJobs = new List<Artera_Job__c>();
        List<Artera_Resource__c> res = new List<Artera_Resource__c>();
        List<Messaging.SingleEmailMessage> mailList =  new List<Messaging.SingleEmailMessage>();
        // System.debug('Mail list: ' + mailList);
        
        for(Leave__c l: leaveLists) {
            if(l.Half_Day_Leave__c == true && (l.Status__c == 'Approved' || l.Status__c == 'Rejected')){
                Date currentDate=l.Leave_Start_date__c; 
                
                Artera_Job__c j;
                
                try{                        
                    j = [SELECT Id, Name, Status__c FROM Artera_Job__c 
                         WHERE Job_Type__c = 'Leave' 
                         AND Job_Date__c =: currentDate
                         AND Status__c != 'Completed'];
                }catch(Exception e){
                    j=null; 
                    // System.debug('j =' +j);
                }
                
                if(j==null){
                    j = new Artera_Job__c();                         
                    List<Project__c> projectId = [SELECT Id,Name FROM Project__c WHERE Name='HydroX Leave' LIMIT 1];
                    Id proId = projectId[0].Id;          	           
                    RecordType rt = [SELECT Id , DeveloperName FROM RecordType WHERE DeveloperName= 'Internal'];
                    j.RecordTypeId = rt.Id;
                    Account acc = [SELECT Id, Name FROM Account Where Name = 'Hydroexcavators, LLC'];
                    j.Account__c = acc.Id;
                    j.Job_Type__c = 'Leave';
                    j.Job_Date__c = currentDate;
                    j.Project__c  = proId;
                    // newJob.Job_Date__c = currentDate;
                    newjobs.add(j);
                    // System.debug('If logger');
                    insert j;
                }
                
                Artera_Job_Allocation__c ja = new Artera_Job_Allocation__c();
                
                Time Timess=l.Leave_Start_Time__c;
                DateTime dt = Timess != null && currentDate != null ? DateTime.newInstanceGMT(currentDate, Timess) : null;
                Time endtime;
                if(dt != null){
                    dt=dt.addHours(4);
                    endtime =dt.timeGmt();
                } else {
                    endtime = null;
                }
                ja.Job__c = j.Id;                   
                ja.Type__c = 'Leave';
                ja.Status__c = 'Assigned';
                ja.Paycode__c = l.Reason__c;
                ja.Half_Day_Leave__c =l.Half_Day_Leave__c;
                ja.Start_Time__c=l.Leave_Start_Time__c;
                ja.End_Time__c=endtime;
                ja.Artera_Resource__c = l.Artera_Resource__c;
                ja.Job_Assignment_Date_Field__c = currentDate;
                // System.debug('else logger');
                // System.debug('Current Date :'+currentDate);
                jobs.add(ja);
                currentDate=currentDate+1;  
                
                
                System.debug('l.Half_Day_Leave__c ' + l.Half_Day_Leave__c);
                Artera_Resource__c resourceList = [SELECT Id,  Name, Email__c  FROM Artera_Resource__c WHERE Id=:l.Artera_Resource__c];
                List<String> toAddresses = new List<String>();
                toAddresses.add(resourceList.Email__c);
                Map<String, String> toSubject=new Map<String,String>();
                Map<String, String> toBody= new Map<String, String>{
                    'ArteraResourceName' => resourceList.Name,
                        'LeaveStatus' => l.Status__c,
                        'startDate' => string.valueOf(l.Leave_Start_date__c)
                        };
                            
                            EmailUtilities.sendResultEmail('Half day leave',toAddresses,toSubject,toBody);   
                break;
            }
            
            
            if(l.Status__c == 'Approved'){    
                iDays = l.Leave_Start_date__c.daysBetween(l.Leave_End_Date__c); 
                Date currentDate=l.Leave_Start_date__c; 
                for (Integer i = 0; i <= iDays; i++) {
                    
                    Artera_Job__c j;
                    
                    try{                        
                        j = [SELECT Id, Name, Status__c FROM Artera_Job__c 
                             WHERE Job_Type__c = 'Leave' 
                             AND Job_Date__c =: currentDate
                             AND Status__c != 'Completed'];
                    }catch(Exception e){
                        j=null; 
                    }
                    
                    if(j==null){
                        j = new Artera_Job__c();                         
                        List<Project__c> projectId = [SELECT Id,Name FROM Project__c WHERE Name='HydroX Leave' LIMIT 1];
                        Id proId = projectId[0].Id;          	           
                        RecordType rt = [SELECT Id , DeveloperName FROM RecordType WHERE DeveloperName= 'Internal'];
                        j.RecordTypeId = rt.Id;
                        Account acc = [SELECT Id, Name FROM Account Where Name = 'Hydroexcavators, LLC'];
                        j.Account__c = acc.Id;
                        j.Job_Type__c = 'Leave';
                        j.Job_Date__c = currentDate;
                        j.Project__c  = proId;
                        // newJob.Job_Date__c = currentDate;
                        newjobs.add(j);
                        // System.debug('If logger');
                        insert j;
                    }
                    
                    Artera_Job_Allocation__c ja = new Artera_Job_Allocation__c();
                    
                    Time Timess=l.Leave_Start_Time__c;
                    DateTime dt = Timess != null && currentDate != null ? DateTime.newInstanceGMT(currentDate, Timess) : null;
                    Time endtime;
                    if(dt != null){
                        dt=dt.addHours(4);
                        endtime =dt.timeGmt();
                    } else {
                        endtime = null;
                    }
                    ja.Job__c = j.Id;                   
                    ja.Type__c = 'Leave';
                    ja.Status__c = 'Assigned';
                    ja.Paycode__c = l.Reason__c;
                    ja.Half_Day_Leave__c =l.Half_Day_Leave__c;
                    ja.Start_Time__c=l.Leave_Start_Time__c;
                    ja.End_Time__c=endtime;
                    ja.Artera_Resource__c = l.Artera_Resource__c;
                    ja.Job_Assignment_Date_Field__c = currentDate;
                    // System.debug('else logger');
                    // System.debug('Current Date :'+currentDate);
                    jobs.add(ja);
                    currentDate=currentDate+1;  
                }  
                
                Artera_Resource__c resourceList = [SELECT Id,  Name, Email__c  FROM Artera_Resource__c WHERE Id=:l.Artera_Resource__c];
                List<String> toAddresses = new List<String>();
                toAddresses.add(resourceList.Email__c);
                Map<String, String> toSubject=new Map<String,String>();
                Map<String, String> toBody= new Map<String, String>{
                    'ArteraResourceName' => resourceList.Name,
                        'LeaveStatus' => l.Status__c,
                        'startDate' => string.valueOf(l.Leave_Start_date__c),
                        'endDate' => string.valueOf(l.Leave_End_Date__c)
                        };
                            EmailUtilities.sendResultEmail('Send Leave Status if approved',toAddresses,toSubject,toBody);
            } 
            
            if (l.Status__c == 'Rejected'){              
                Artera_Resource__c resourceList = [SELECT Id,  Name, Email__c  FROM Artera_Resource__c WHERE Id=:l.Artera_Resource__c];
                List<String> toAddresses = new List<String>();
                toAddresses.add(resourceList.Email__c);
                Map<String, String> toSubject=new Map<String,String>();
                Map<String, String> toBody= new Map<String, String>{
                    'ArteraResourceName' => resourceList.Name,
                        'LeaveStatus' => l.Status__c,
                        'ReasonForRejection' => l.Reason_for_leave_rejection__c,
                        'startDate' => string.valueOf(l.Leave_Start_date__c),
                        'endDate' => string.valueOf(l.Leave_End_Date__c)
                        };
                            
                            EmailUtilities.sendResultEmail('Send Leave Status if rejected',toAddresses,toSubject,toBody);        
            }
        }
        if(jobs.size()>0){
            insert jobs;
        }
    }
    public static void justIncrement() {
        Integer i = 0;
        i++;
        i++;
		i++;
        i++;
        i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
         i++;
        i++;
		i++;
        i++;
        i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
         i++;
        i++;
		i++;
        i++;
        i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
         i++;
        i++;
		i++;
        i++;
        i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
         i++;
        i++;
		i++;
        i++;
        i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
         i++;
        i++;
		i++;
        i++;
        i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;
         i++;
        i++;
		i++;
        i++;
        i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
         i++;
        i++;
		i++;
        i++;
        i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;
         i++;
        i++;
		i++;
        i++;
        i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
         i++;
        i++;
		i++;
        i++;
        i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;
         i++;
        i++;
		i++;
        i++;
        i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
         i++;
        i++;
		i++;
        i++;
        i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;
         i++;
        i++;
		i++;
        i++;
        i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
         i++;
        i++;
		i++;
        i++;
        i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;
         i++;
        i++;
		i++;
        i++;
        i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
         i++;
        i++;
		i++;
        i++;
        i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;
         i++;
        i++;
		i++;
        i++;
        i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
         i++;
        i++;
		i++;
        i++;
        i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;
         i++;
        i++;
		i++;
        i++;
        i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
         i++;
        i++;
		i++;
        i++;
        i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
        i++;i++;
        i++;
		i++;
    }   
}