objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Artera_Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Job Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Assignment in Progress</fullName>
                </value>
                <value>
                    <fullName>Dispatched</fullName>
                </value>
                <value>
                    <fullName>Dispatched - Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Pending Supervisor Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Admin Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Billing Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Payroll Approval</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Company__c</field>
                <operation>equals</operation>
                <value>025</value>
            </filterItems>
            <filterItems>
                <field>Account.Status__c</field>
                <operation>equals</operation>
                <value>A</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Hydro_X_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Date__c</fullName>
        <label>Job Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Job_Location__c</fullName>
        <label>Job Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Approve_Ticket__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approve Ticket?</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Artera_Job_Allocation__c.object
<CustomObject>
    <label>Job Assignment</label>
    <nameField>
        <displayFormat>JAN-{0000}</displayFormat>
        <label>Job Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Artera_Job__c</referenceTo>
        <relationshipName>Job_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unassigned</fullName>
                    <default>true</default>
                    <label>Unassigned</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                    <isActive>false</isActive>
                    <label>Declined</label>
                </value>
                <value>
                    <fullName>Dispatch</fullName>
                    <isActive>false</isActive>
                    <label>Dispatch</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Per_Diem__c</fullName>
        <label>Per Diem</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lunch_Time__c</fullName>
        <defaultValue>30</defaultValue>
        <label>Lunch Time (in mins)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <formula>Artera_Resource__r.Employee_ID__c</formula>
        <label>Employee ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Artera_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Artera_Resource__c.Worker_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Artera_Resource__c</referenceTo>
        <relationshipLabel>Job Assignments</relationshipLabel>
        <relationshipName>Hydro_X_Job_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Artera_Resource__c.object
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <externalId>true</externalId>
        <label>Employee ID</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Hydro_X_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Job_Ticket__c.object
<CustomObject>
    <label>Job Ticket</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Job Ticket Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Job1__c</fullName>
        <label>Job</label>
        <referenceTo>Artera_Job__c</referenceTo>
        <relationshipLabel>Job Tickets</relationshipLabel>
        <relationshipName>Job_Tickets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#FF0000</color>
                    <label>Cancelled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Time</type>
    </fields>
</CustomObject>

objects/Job_Ticket_Detail__c.object
<CustomObject>
    <label>Job Ticket Detail</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Job Ticket Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Tickets Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Artera_Job__c</referenceTo>
        <relationshipLabel>Job Tickets Detail</relationshipLabel>
        <relationshipName>Job_Tickets_Detail</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job_Date__c</fullName>
        <formula>Job_Ticket__r.Job1__r.Job_Date__c</formula>
        <label>Job Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <formula>LEFT(Job_Ticket__r.Location__c,30)</formula>
        <label>Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Ticket__c</fullName>
        <label>Job Ticket</label>
        <referenceTo>Job_Ticket__c</referenceTo>
        <relationshipLabel>Job Tickets Detail</relationshipLabel>
        <relationshipName>Job_Tickets_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

classes/dailyWorkJobTicketCtrTest.cls
@isTest
public class dailyWorkJobTicketCtrTest {

    @isTest
    public static void testMethod1(){
        Account acc =new Account();
        acc.Name = 'Test Account';
        insert acc;
        
        
        Artera_Job__c job1 = new Artera_Job__c();
        //job1.Name = 'f tFilling';
        job1.Status__c ='Dispatched - Acknowledged';
        job1.Job_Date__c = System.today();
        job1.account__c = acc.Id;
        job1.Job_Location__c = 'test location';
        insert job1;
        
        
        Artera_Job__c job2 = new Artera_Job__c();
        //job2.Name = 'f tFilling';
        job2.Status__c ='Dispatched';
        job2.Job_Date__c = System.today();
        job2.account__c = acc.Id;
        job2.Job_Location__c = 'test location';
        insert job2;
        
       User u = [select Id , firstname from user where id=:userinfo.getuserid()];
            
        Artera_Resource__c resource = new Artera_Resource__c(); 
        resource.Name = 'test operator';
        resource.Email__c = 'aamir@bugendaitech.com';
        resource.Salesforce_User__c = u.Id;
        resource.Employee_ID__c = 'test emp';
        insert resource; 
        
          Artera_Resource__c resource1 = new Artera_Resource__c(); 
        resource1.Name = 'Kamil Kamran';
        resource1.Email__c = 'kkamran336@gmail.com';
        resource1.Salesforce_User__c = u.Id;
        resource1.Employee_ID__c = 'test emp1';
        insert resource1; 
        
        
        
        Artera_Job_Allocation__c alloc = new Artera_Job_Allocation__c();
        alloc.Artera_Resource__c = resource.Id;
        alloc.Job__c = job1.Id ;
        alloc.Start_Time__c = null; 
        alloc.End_Time__c = null;
		alloc.Lunch_Time__c =20;
        alloc.Per_Diem__c = 'Yes';
		insert alloc;
        
        Job_Ticket__c jobticket = new Job_Ticket__c();
        jobticket.Job1__c = job1.id;
        jobticket.Location__c='Atlanta';
        insert jobticket;
        
        Artera_Job__c Job_for_ticket = new Artera_Job__c();
        //job1.Name = 'f tFilling';
        Job_for_ticket.Status__c ='Dispatched';
        Job_for_ticket.Job_Date__c = System.today();
        Job_for_ticket.account__c = acc.Id;
        Job_for_ticket.Approve_Ticket__c = False;
		Job_for_ticket.Job_Location__c = 'test location';
        insert Job_for_ticket;
        Id JobId = Job_for_ticket.Id ;
        
        
        List<Job_Ticket_Detail__c> jobtickdetailsList = new List<Job_Ticket_Detail__c>();
        for(Integer i=0;i<2;i++){
            Job_Ticket_Detail__c jobticketdetails = new Job_Ticket_Detail__c();
            jobticketdetails.Job_Ticket__c = jobticket.Id;
            jobtickdetailsList.add(jobticketdetails);        
        }
        insert jobtickdetailsList;
		//For Both 0 ----------------------------------------------------------------------------------
        Artera_Job__c job3 = new Artera_Job__c();
        job3.Status__c ='Dispatched - Acknowledged';
        job3.Job_Date__c = System.today();
        job3.account__c = acc.Id;
        job3.Job_Location__c = 'test location';
        insert job3;
        
        //For hydroXJob =1 and hydroXDetails = 0-------------------------------------------------------
        Artera_Job__c job4 = new Artera_Job__c();
        job4.Status__c ='Dispatched - Acknowledged';
        job4.Job_Date__c = System.today();
        job4.account__c = acc.Id;
        job4.Job_Location__c = 'test location';
        insert job4;
        
         Artera_Job_Allocation__c alloc2 = new Artera_Job_Allocation__c();
        alloc2.Artera_Resource__c = resource.Id;
        alloc2.Job__c = job4.Id ;
        alloc2.Start_Time__c = null; 
        alloc2.End_Time__c = null;
		alloc2.Lunch_Time__c =20;
        alloc2.Per_Diem__c = 'Yes';
		insert alloc2;
        
          Job_Ticket__c jobticket1 = new Job_Ticket__c();
        jobticket1.Job1__c = job4.id;
        jobticket1.Location__c='Atlanta';
        insert jobticket1;
        
        
        
        Test.startTest();
        dailyWorkJobTicketCtr MyWorkTicket = new dailyWorkJobTicketCtr(); 
        dailyWorkJobTicketCtr.updateSignedBy('KamilK' , True , JobId );
        dailyWorkJobTicketCtr.getJobDetailsByJobId(job1.Id);
        dailyWorkJobTicketCtr.getJobDetails(job1.Id);
        dailyWorkJobTicketCtr.getAllJobTicketsByJobId(job1.Id);
        dailyWorkJobTicketCtr.getAllJobTicketsAllocationDetailsById(job3.id);
          dailyWorkJobTicketCtr.getAllJobTicketsAllocationDetailsById(job4.id);
        System.runAs(u) {
        dailyWorkJobTicketCtr.getAllJobAllocationsByJobId(job1.Id);
        }
        dailyWorkJobTicketCtr.getTicketsDetailsById(jobticket.Id);
        Test.stopTest();
        System.assertEquals('error', dailyWorkJobTicketCtr.getAllJobTicketsAllocationDetailsById(job4.id));
        
    }
     @isTest
     static  void testIncrement() {
         Test.startTest();
        dailyWorkJobTicketCtr.justIncrement();
 		Test.stopTest();
     }
}