objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Artera_Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Job Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Assignment in Progress</fullName>
                </value>
                <value>
                    <fullName>Dispatched</fullName>
                </value>
                <value>
                    <fullName>Dispatched - Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Pending Supervisor Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Admin Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Billing Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Payroll Approval</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job_Date__c</fullName>
        <label>Job Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Location__c</fullName>
        <label>Job Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Artera_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Area</label>
        <referenceTo>Artera_Region__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Hydro_X_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Artera_Job_Allocation__c.object
<CustomObject>
    <label>Job Assignment</label>
    <nameField>
        <displayFormat>JAN-{0000}</displayFormat>
        <label>Job Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Artera_Job__c</referenceTo>
        <relationshipName>Job_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unassigned</fullName>
                    <default>true</default>
                    <label>Unassigned</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                    <isActive>false</isActive>
                    <label>Declined</label>
                </value>
                <value>
                    <fullName>Dispatch</fullName>
                    <isActive>false</isActive>
                    <label>Dispatch</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <formula>Artera_Resource__r.Employee_ID__c</formula>
        <label>Employee ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Artera_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Artera_Resource__c.Worker_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Artera_Resource__c</referenceTo>
        <relationshipLabel>Job Assignments</relationshipLabel>
        <relationshipName>Hydro_X_Job_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Artera_Region__c.object
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Artera Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Region</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <scale>8</scale>
        <type>Location</type>
    </fields>
</CustomObject>

objects/Artera_Resource__c.object
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Hydro_X_Resources1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <externalId>true</externalId>
        <label>Employee ID</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Artera_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Artera Region</label>
        <referenceTo>Artera_Region__c</referenceTo>
        <relationshipName>Artera_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Job_Ticket__c.object
<CustomObject>
    <label>Job Ticket</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Job Ticket Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Job1__c</fullName>
        <label>Job</label>
        <referenceTo>Artera_Job__c</referenceTo>
        <relationshipLabel>Job Tickets</relationshipLabel>
        <relationshipName>Job_Tickets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#FF0000</color>
                    <label>Cancelled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/supervisorCtrTest.cls
@isTest
public with sharing class supervisorCtrTest {
    @isTest
    public static void getAllStatusTest(){
        supervisorCtr.PROFILENAME_TEST = 'Hydro-X Supervisor';

        System.Test.startTest();
            List<String> allStatus = SupervisorCtr.getAllStatus();
         	SupervisorCtr.PROFILENAME_TEST = 'Hydro-X Supervisor';
            allStatus = SupervisorCtr.getAllStatus();
            SupervisorCtr.PROFILENAME_TEST = 'Hydro-X Admin';
            allStatus = SupervisorCtr.getAllStatus();
            SupervisorCtr.PROFILENAME_TEST = 'Hydro-X Account Receivables';
            allStatus = SupervisorCtr.getAllStatus();
            SupervisorCtr.PROFILENAME_TEST = 'System Administrator';
            allStatus = SupervisorCtr.getAllStatus();

        System.Test.stopTest();
    }

    @isTest
    public static void approveJobsTest(){
        supervisorCtr.PROFILENAME_TEST = 'Hydro-X Supervisor';
        //Artera_Job__c theJob = new Artera_Job__c(/*Name = 'Test Job'*/);
        Artera_Job__c theJob = new Artera_Job__c();
        insert theJob;
        List<String> jobIds = new List<String>{theJob.Id};

        System.Test.startTest();       
            SupervisorCtr.approveJobs(jobIds);
        	SupervisorCtr.PROFILENAME_TEST = 'Hydro-X Supervisor';
        	SupervisorCtr.approveJobs(jobIds);
            SupervisorCtr.PROFILENAME_TEST = 'Hydro-X Admin';
            SupervisorCtr.approveJobs(jobIds);
            SupervisorCtr.PROFILENAME_TEST = 'Hydro-X Account Receivables';
            SupervisorCtr.approveJobs(jobIds);
            SupervisorCtr.PROFILENAME_TEST = 'System Administrator';
            SupervisorCtr.approveJobs(jobIds);
        System.Test.stopTest();
    }

    @isTest
    public static void getSearchListTest(){
        supervisorCtr.PROFILENAME_TEST = 'Hydro-X Supervisor';
        List<String> allStatus = SupervisorCtr.getAllStatus();

        Id userId = UserInfo.getUserId(); 
        Artera_Job__c theJob = new Artera_Job__c(
            //Name = 'Test Job a',
            Supervisor__c = userId, Status__c = allStatus[0],
            Job_Date__c = System.today()
        );
        Artera_Region__c reg = new Artera_Region__c(name = 'FL - Tampa');
        String regionName = 'FL - Tampa';
        List<String> regList = new List<String>();
        regList.add(regionName);
        insert theJob;

        System.Test.startTest();
            SupervisorCtr.getSearchListByFilter('My', '', null,regList);
            SupervisorCtr.getSearchListByFilter('All','a',null,regList);
            
            SupervisorCtr.PROFILENAME_TEST = 'System Administrator';
            theJob = new Artera_Job__c(
                // Name = 'Test Job b', 
                Supervisor__c = userId, Status__c = 'Assignment in Progress',
                Job_Date__c = System.today()
            );
            insert theJob;
            SupervisorCtr.getSearchListByFilter('My', '', null, regList);
            SupervisorCtr.getSearchListByFilter('All', 'a', null, regList);
        System.Test.stopTest();

    }

    @isTest
    public static void getSearchListByDateTest(){
        supervisorCtr.PROFILENAME_TEST = 'Hydro-X Supervisor';
        List<String> allStatus = SupervisorCtr.getAllStatus();

        Id userId = UserInfo.getUserId(); 
        Artera_Job__c theJob = new Artera_Job__c(
            //Name = 'Test Job a', 
            Supervisor__c = userId, Status__c = allStatus[0],
            Job_Date__c = System.today()
        );
        insert theJob;

    }

    @isTest
    public static void getAllJobAllocationsForSupervisorTest(){
        supervisorCtr.PROFILENAME_TEST = 'Hydro-X Supervisor';
        List<String> allStatus = SupervisorCtr.getAllStatus();

        Id userId = UserInfo.getUserId(); 

        Artera_Resource__c resource = new Artera_Resource__c();
                resource.Name = 'Test Resource';
                resource.Employee_ID__c = 'Emp-23251329';
                resource.Email__c = 'simran.vyas@bugendaitech.com';
                insert resource;
        
        Artera_Job__c jobrec= new Artera_Job__c();
        
                jobrec.Job_Date__c= Date.today();
                jobrec.Job_Location__c = 'NYC Testing Job'; 
        		jobrec.Status__c = 'Pending Supervisor Approval'; 
                insert jobrec;     
                     
        Artera_Job_Allocation__c jobAllocation = new Artera_Job_Allocation__c();
                jobAllocation.Artera_Resource__c = resource.Id;
                jobAllocation.Job__c = jobrec.Id;
                insert  jobAllocation; 
         
        List<Job_Ticket__c> jobTktList = new List<Job_Ticket__c>();
                for(Integer i=1; i<5 ; i++){
                    Job_Ticket__c jobTktObj = new Job_Ticket__c();
                    jobTktObj.Location__c = 'Location '+i;
                    jobTktObj.job1__c = jobrec.Id;
                    jobTktList.add(jobTktObj);
                }
                insert jobTktList;
         

        System.Test.startTest(); 
            SupervisorCtr.getAllJobAllocationsForSupervisor('All');


            SupervisorCtr.PROFILENAME_TEST = 'System Administrator';
                Artera_Job__c jobrec2 = new Artera_Job__c(); 
                jobrec2.Job_Date__c= Date.today();
                jobrec2.Job_Location__c = 'NYC Testing Job 2'; 
        		jobrec2.Status__c = 'Pending Admin Approval'; 
                insert jobrec2; 
        	SYstem.debug('Data s '+jobrec2);
            SupervisorCtr.getAllJobAllocationsForSupervisor('All');
        System.Test.stopTest();

    }

    

    @isTest
    public static void wrappersCoverageTest(){
        supervisorCtr.PROFILENAME_TEST = 'Hydro-X Supervisor';
        Id userId = UserInfo.getUserId(); 
        List<String> allStatus = SupervisorCtr.getAllStatus();
        Artera_Job__c theJob = new Artera_Job__c(
            //Name = 'Test Job a', 
            Supervisor__c = userId, Status__c = allStatus[0],
            Job_Date__c = System.today()
        );
        insert theJob;
        Artera_Resource__c res = new Artera_Resource__c(
            Employee_ID__c = '12345'
        );
        Artera_Resource__c artRes = new Artera_Resource__c(
            Name = 'someTest Name',
            Employee_ID__c = '12345'
        );
        insert artRes;
        Artera_Job_Allocation__c joal = new Artera_Job_Allocation__c(
            Artera_Resource__c = artRes.Id,
            Job__c = theJob.Id
        );
        insert joal;
        System.Test.startTest();
            SupervisorCtr.JobAllocWrapper jaw = new SupervisorCtr.JobAllocWrapper(
                theJob.Id,
                theJob.Name,
                theJob.Id,
                theJob.Name,
                theJob.Name,
                theJob.Name
            );
            jaw = new SupervisorCtr.JobAllocWrapper(
                new Artera_Job_Allocation__c(),
                theJob.Id,
                theJob.Name,
                theJob.Id,
                theJob.Name,
                theJob.Name,
                theJob.Name
            );
            jaw = new SupervisorCtr.JobAllocWrapper(
                joal
            );
            jaw = new SupervisorCtr.JobAllocWrapper(
                new Artera_Job_Allocation__c(
                    Job__c = theJob.Id
                )
            );


            SupervisorCtr.tktDetWrapper tktdtl = new SupervisorCtr.tktDetWrapper(
                theJob.Id, theJob.Name
            );
            SupervisorCtr.JobTicketWrapper jtw = new SupervisorCtr.JobTicketWrapper(
                theJob.Id, theJob.Name, new List<SupervisorCtr.tktDetWrapper> {tktdtl}
            );

            SupervisorCtr.ResponseData resData = new SupervisorCtr.ResponseData(
                new List<SupervisorCtr.JobDetailsWrapper>(), 2
            );
        
        supervisorCtr.getAllJobAllocationsForSupervisorRefreshData('All');
        System.Test.stopTest();
    }
    
    @isTest
     static  void testIncrement() {
         Test.startTest();
        supervisorCtr.justIncrement();
 		Test.stopTest();
     }
    
}