objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Artera_Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Job Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Assignment in Progress</fullName>
                </value>
                <value>
                    <fullName>Dispatched</fullName>
                </value>
                <value>
                    <fullName>Dispatched - Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Pending Supervisor Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Admin Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Billing Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Payroll Approval</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Company__c</field>
                <operation>equals</operation>
                <value>025</value>
            </filterItems>
            <filterItems>
                <field>Account.Status__c</field>
                <operation>equals</operation>
                <value>A</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Hydro_X_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Date__c</fullName>
        <label>Job Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Job_Location__c</fullName>
        <label>Job Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Artera_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Area</label>
        <referenceTo>Artera_Region__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Hydro_X_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Artera_Region__c.object
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Artera Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Region</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Artera_Resource__c.object
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset__c</referenceTo>
        <relationshipLabel>Resources</relationshipLabel>
        <relationshipName>Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <externalId>true</externalId>
        <label>Employee ID</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Artera_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Artera Region</label>
        <referenceTo>Artera_Region__c</referenceTo>
        <relationshipName>Artera_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Asset__c.object
<CustomObject>
    <label>Asset</label>
    <nameField>
        <label>Asset ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Asset_Type__c</fullName>
        <label>Asset Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Truck</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/TruckAvailabiltyCtrlTest.cls
@isTest(seeAllData=True)
public class TruckAvailabiltyCtrlTest {
    
    @isTest
    public static void testMethod1(){
        Artera_Region__c art = new Artera_Region__c();
        art.Name = 'GA - Conyers';
        insert art;
        List<String> listArt = new List<String>();
        listArt.add(art.id);
        
        Account acc =new Account();
        acc.Name = 'Test Account 1';
        insert acc;
        
        Artera_Job__c job1 = new Artera_Job__c();
        job1.Status__c ='Dispatched - Acknowledged';
        job1.Job_Date__c = System.today().addDays(1);
        job1.account__c = acc.Id;
        job1.Job_Location__c = 'test location';
        insert job1;
        
        Asset__c asset = new Asset__c();
        asset.Name = '0005';
        asset.Asset_Type__c = 'Truck';
        insert asset; 
        
        Artera_Resource__c resource = new Artera_Resource__c();
        resource.Name = 'test operator';
        resource.Artera_Region__c = art.Id;
        resource.Email__c = 'ritisha.chavan@artera.com';
        resource.Employee_ID__c = 'test emp';
        insert resource; 
        
        Test.startTest();
        TruckAvailabiltyCtrl.getRegionList();
        TruckAvailabiltyCtrl.getAllAsset();
        TruckAvailabiltyCtrl.getAllAssetsByFilters(resource.Name, null, listArt);
        Test.stopTest();
        
    }
    
    
    @isTest
    public static void testMethod2(){
        Artera_Region__c art = new Artera_Region__c();
        art.Name = 'GA - Conyers';
        insert art;
        List<String> listArt = new List<String>();
        listArt.add(art.id);
        
        Account acc =new Account();
        acc.Name = 'Test Account 2';
        insert acc;
        
        Artera_Job__c job2 = new Artera_Job__c();
        job2.Status__c ='Dispatched - Acknowledged';
        Date fDate = Date.newInstance(2012, 04, 22);
        job2.Job_Date__c = fDate;
        job2.account__c = acc.Id;
        job2.Job_Location__c = 'test location';
        insert job2;
        
        Asset__c asset = new Asset__c();
        asset.Name = '0005';
        asset.Asset_Type__c = 'Truck';
        insert asset;
        
        Artera_Resource__c resource = new Artera_Resource__c();
        resource.Name = 'test operator';
        resource.Artera_Region__c = art.Id;
        resource.Email__c = 'ritisha.chavan@artera.com';
        resource.Employee_ID__c = 'test emp';
        insert resource; 
        
        Test.startTest();
        TruckAvailabiltyCtrl.getRegionList();
        TruckAvailabiltyCtrl.getAllAsset();
        TruckAvailabiltyCtrl.getAllAssetsByFilters(resource.Name, fDate, listArt);
        Test.stopTest();
        
    } 
}