objects/Artera_Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Job_Date__c</fullName>
        <label>Job Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Artera_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Area</label>
        <referenceTo>Artera_Region__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Hydro_X_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Artera_Region__c.object
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Artera Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Region</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JobShareTriggerTest.cls
@isTest
private class JobShareTriggerTest {

    
 static testMethod void shareJobTest(){
     List<Artera_Job__c> job = new LisT<Artera_Job__c>();
     Artera_Job__c j = new Artera_Job__c();
     Artera_Region__c region = new Artera_Region__c();
     
    
     j.Job_Date__c = Date.newInstance(2022, 05, 21);
     j.Artera_Region__c = region.Name;
     region.Name = 'FL-Tampa';

     List<Artera_Job__Share> jShrs = [SELECT Id, UserOrGroupId, AccessLevel, 
         RowCause FROM Artera_Job__Share WHERE ParentId = :j.Id];
    insert j;
 
 
 
 }
}