objects/Artera_Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Job_Date__c</fullName>
        <label>Job Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Job_Location__c</fullName>
        <label>Job Location</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

classes/jobTicketPicklistTest.cls
@isTest
private class jobTicketPicklistTest {
    
    @isTest
    public static void positiveScenarioTest(){
        
        // test data
        
        Artera_Job__c artJob = new Artera_Job__c();
        
        
        //artJob.Name             = 'Test Job Name';
        artJob.Job_Location__c  = 'Location Name';
        artJob.Job_Date__c      = Date.today();
        
        
        insert artJob;
        
        Test.startTest();        
        jobTicketPicklist.getTicketNumberLists(artJob.Id);
        Test.stopTest();
    }
    
    
}