objects/Artera_Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Job Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Assignment in Progress</fullName>
                </value>
                <value>
                    <fullName>Dispatched</fullName>
                </value>
                <value>
                    <fullName>Dispatched - Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Pending Supervisor Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Admin Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Billing Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Payroll Approval</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project__c.Status__c</field>
                <operation>equals</operation>
                <value>A</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Date__c</fullName>
        <label>Job Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Owner_Name__c</fullName>
        <formula>Owner:User.FirstName&amp;&apos; &apos;&amp;Owner:User.LastName</formula>
        <label>Owner Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Location__c</fullName>
        <label>Job Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Dispatcher_Notes__c</fullName>
        <label>Dispatcher Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

objects/Artera_Job_Allocation__c.object
<CustomObject>
    <label>Job Assignment</label>
    <nameField>
        <displayFormat>JAN-{0000}</displayFormat>
        <label>Job Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Artera_Job__c</referenceTo>
        <relationshipName>Job_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unassigned</fullName>
                    <default>true</default>
                    <label>Unassigned</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                    <isActive>false</isActive>
                    <label>Declined</label>
                </value>
                <value>
                    <fullName>Dispatch</fullName>
                    <isActive>false</isActive>
                    <label>Dispatch</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>Job__r.Project__r.Project_Id__c</formula>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Artera_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Artera_Resource__c.Worker_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Artera_Resource__c</referenceTo>
        <relationshipLabel>Job Assignments</relationshipLabel>
        <relationshipName>Hydro_X_Job_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Artera_Resource__c.object
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset__c</referenceTo>
        <relationshipLabel>Resources</relationshipLabel>
        <relationshipName>Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Hydro_X_Resources1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Hydro_X_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Asset__c.object
<CustomObject>
    <label>Asset</label>
    <nameField>
        <label>Asset ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/rsplus__SMS_Bucket__c.object
<CustomObject>
</CustomObject>

classes/JobStatusCancelledHandler.cls
public class JobStatusCancelledHandler {
    
    public static List<rsplus__SMS_Bucket__c> SmsToSend = new List<rsplus__SMS_Bucket__c>();
    public static rsplus__SMS_Bucket__c SendSMSToOperatorWithNotes (Artera_Job_Allocation__c ArtJobAlloc)
    {   
        rsplus__SMS_Bucket__c SMS = new rsplus__SMS_Bucket__c();
        
        SMS.rsplus__Number__c =ArtJobAlloc.Artera_Resource__r.Phone_Number__c;
        
        SMS.rsplus__Related_To__c =ArtJobAlloc.Id ;
        SMS.rsplus__Sender_ID__c = '14707305812';
        SMS.rsplus__Template_ID__c = 'T0005';
        
        return SMS ;
        
    }
    
    public static void onStatusChange(List<Artera_Job__c> jobList, Map<Id, Artera_Job__c> oldjobList){  
        List<Messaging.SingleEmailMessage> ListEmails = new List<Messaging.SingleEmailMessage>();
        Messaging.SingleEmailMessage SingleEmail = new Messaging.SingleEmailMessage();
        
        List<Artera_Job_Allocation__c> jobAllocationsToUpdate = new List<Artera_Job_Allocation__c>();
        List<rsplus__SMS_Bucket__c> ListSMS = new List<rsplus__SMS_Bucket__c>();
        rsplus__SMS_Bucket__c SingleMessage = new rsplus__SMS_Bucket__c();       
        
        List<Artera_Job_Allocation__c> JobAlls = new List<Artera_Job_Allocation__c> ();
        JobAlls = [SELECT Id , Name ,Status__c,Job__r.Name, Job__c ,Job__r.Asset__c,Job__r.RecordTypeId, Artera_Resource__c , Job__r.Dispatcher_Notes__c ,Job__r.Id, 
                   Artera_Resource__r.Phone_Number__c ,Artera_Resource__r.Name,Artera_Resource__r.Supervisor__r.Email,Job__r.supervisor__r.Name,
                   Job__r.Start_Date__c, Artera_Resource__r.Supervisor__r.Name,Job__r.Job_Date__c,Job__r.Job_Location__c,
                   Job__r.Owner_Name__c,Job__r.Project__r.Id,Job__r.Project__r.Name,Job__r.Contact__r.Name,Job__r.Contact__r.Phone,Job__r.Status__c,
                   Artera_Resource__r.Email__c,Artera_Resource__r.Supervisor__r.MobilePhone,Job__r.RecordTYPE.DEVELOPERName,
                   Artera_Resource__r.Salesforce_User__c,Artera_Resource__r.Supervisor__c
                   FROM Artera_Job_Allocation__c WHERE Job__c IN:jobList ];                
        
        
        for(Artera_Job_Allocation__c ja : JobAlls){
            Artera_Job__c oldJobs = oldjobList.get(ja.Job__r.Id);
                        System.debug('ja.Job__r.Id '+ja.Job__r.Id);
            System.debug('new job '+ja.Job__r.Status__c);
            System.debug('oldjobList' +oldjobList);
            System.debug('old job '+oldJobs.Status__c);
            
            if(ja.Job__r.Status__c == 'Cancelled' && (oldJobs.Status__c == 'Dispatched - Acknowledged' || oldJobs.Status__c == 'Dispatched')){
                System.debug('#################################Cancel Handler Running');
                EmailTemplate jobCancelledTemplate = [SELECT Id,Name,Subject,Markup FROM EmailTemplate WHERE Name = 'Job Cancelled'];
                List<string> toAddresses = new List<string>();
                toAddresses.add(ja.Artera_Resource__r.Email__c);
                Map<string ,string> toSubject = new Map<string , string>{                        
                };
                    Map<string ,string> toBody = new Map<string, string>{  
                        'JobAssignmentName'  => ja.Name, 
                            'ResourceName' => ja.Artera_Resource__r.Name ,
                            'ArteraJobName'  => ja.Job__r.Name ,
                            'ArterajobDate'  => String.valueOf(ja.Job__r.Job_Date__c) ,
                            'LocationJob'   => ja.Job__r.Job_Location__c,
                            'ArteraSupervisorName'   => ja.Job__r.Supervisor__r.Name	
                            };
                                
                                SingleEmail = EmailUtilities.getResultEmail(jobCancelledTemplate ,toAddresses ,toSubject,toBody );
                System.debug('SingleEmail'+SingleEmail);
                
                if (ja.Artera_Resource__r.Email__c != null){
                    //  SingleEmail = EmailUtilities.sendResultEmail('Job Cancelled',toAddresses,toSubject,toBody);
                    ListEmails.add(SingleEmail);  
                    System.debug('only email' + toAddresses);
                }
                if (ja.Artera_Resource__r.Phone_Number__c != null){
                    SingleMessage = SendSMSToOperatorWithNotes(ja);
                    ListSMS.add(SingleMessage);
                    System.debug('only sms'  );
                }
            }else for(Artera_Job_Allocation__c jobAlloc : JobAlls){
                jobAlloc.Status__c = 'Cancelled';
                // jobAllocationsToUpdate.add(jobAlloc); 
            }                    
        }
        Insert ListSMS;
        if(ListEmails != null && !ListEmails.isEmpty())
        {
            Messaging.sendEmail(ListEmails);
        }
    }
    
}