objects/Artera_Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Job_Date__c</fullName>
        <label>Job Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Owner_Name__c</fullName>
        <formula>Owner:User.FirstName&amp;&apos; &apos;&amp;Owner:User.LastName</formula>
        <label>Owner Name</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Artera_Job_Allocation__c.object
<CustomObject>
    <label>Job Assignment</label>
    <nameField>
        <displayFormat>JAN-{0000}</displayFormat>
        <label>Job Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Artera_Job__c</referenceTo>
        <relationshipName>Job_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Artera_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Artera_Resource__c.Worker_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Artera_Resource__c</referenceTo>
        <relationshipLabel>Job Assignments</relationshipLabel>
        <relationshipName>Hydro_X_Job_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Artera_Resource__c.object
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
</CustomObject>

objects/Job_Ticket__c.object
<CustomObject>
    <label>Job Ticket</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Job Ticket Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Job1__c</fullName>
        <label>Job</label>
        <referenceTo>Artera_Job__c</referenceTo>
        <relationshipLabel>Job Tickets</relationshipLabel>
        <relationshipName>Job_Tickets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/SendingEmailUponTicketCreation.cls
/**
@author Simran
@date 21/04/2022
@group Artera_Job__c
@description Apex invocable class for sending mail to resource Upon New Job-ticket creation.
Name :  SendingEmailUponTicketCreation.
@lastModifiedOn 15/04/2022 
@lastModifiedBy simran
*/

public class SendingEmailUponTicketCreation {
    @InvocableMethod(Label='Sending Email On Ticket Creation' Description = 'Sending email on ticket creation')
    public static void SendingEmailToResources(List<Artera_Job__c> ArteraJob ) {
        string jobId = ArteraJOb[0].id ;
        List<string> toAddresses = new List<string>();
        System.debug(jobId+' Id');
        string Operator_Resource_Name ='';
        string Ticket_Id ='';
        string Ticket_Name ='';
        string Ticket_Location = '';
        string Resource_Email ='';
        Artera_Job__c JOB = [SELECT Id ,Name ,Job_Date__c,Owner_Name__c,(SELECT Artera_Resource__r.Name,Artera_Resource__r.Email__c ,ID , Name FROM Job_Allocations__r ),
                             (SELECT Id ,Location__c, Name FROM Job_Tickets__r) 
                             FROM Artera_Job__c WHERE ID =: jobId];
        
        For(Artera_Job_Allocation__c ArtJobAlloc : JOB.Job_Allocations__r)
        {
            if(ArtJobAlloc.Artera_Resource__r.Email__c != Null)
            {
            Operator_Resource_Name = ArtJobAlloc.Artera_Resource__r.Name ;
             Resource_Email =ArtJobAlloc.Artera_Resource__r.Email__c;
            toAddresses.add(Resource_Email);
            }
            else 
                return;
            }
        
        For(Job_Ticket__c Ticket : JOB.Job_Tickets__r ){
		    Ticket_Id = Ticket.Id;
            Ticket_Name =Ticket.Name;
            Ticket_Location =Ticket.Location__c;
            }
        
        Map<string ,string> toSubject = new Map<string , string>();
        Map<string ,string> toBody = new Map<string, string>
        {
            'OperatorResourceName' =>Operator_Resource_Name ,
                'TicketId'  => Ticket_Id,
                'TicketName'       => Ticket_Name ,
                'ArteraJobName'   => JOB.Name ,
                'JobDate'        =>String.valueOf( JOB.Job_Date__c),
                'TicketLocation' => Ticket_Location,
                'JobOwner'   => JOB.Owner_Name__c
                };
             
        EmailUtilities.sendResultEmail('Send email notification to resource' ,toAddresses ,toSubject,toBody );
    }
    
}