objects/Artera_Job_Allocation__c.object
<CustomObject>
    <label>Job Assignment</label>
    <nameField>
        <displayFormat>JAN-{0000}</displayFormat>
        <label>Job Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assignment</fullName>
                </value>
                <value>
                    <fullName>Leave</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Non- Billable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Artera_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Artera_Resource__c.Worker_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Artera_Resource__c</referenceTo>
        <relationshipLabel>Job Assignments</relationshipLabel>
        <relationshipName>Hydro_X_Job_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Assignment_Date_Field__c</fullName>
        <label>Job Assignment Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

objects/Artera_Region__c.object
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Artera Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Region</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Artera_Resource__c.object
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Job_Title__c</fullName>
        <label>Job Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Artera_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Artera Region</label>
        <referenceTo>Artera_Region__c</referenceTo>
        <relationshipName>Artera_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Worker_Status__c</fullName>
        <label>Worker Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/dispatcherCtrl.cls
public with sharing class dispatcherCtrl {

   
    @AuraEnabled(cacheable = true)
    public static List<Artera_Region__c> getRegionList(){
        try {
            List<Artera_Region__c> region = new List <Artera_Region__c> ();
            region = [select Id, Name from Artera_Region__c ];
            region.sort();
            return region;
        } catch (Exception e) { throw new AuraHandledException(e.getMessage()); }
    }
    
    
        @AuraEnabled(cacheable = true)
        public static String getAllResources(){
            try {
                List<resWraCls> resWrapper = new List<resWraCls>();
                Date today    = Date.today();
                Date tomorrow = today.addDays(1);     
                String bgColor;
                String title;
                String retString;
                List<Artera_Resource__c> resList = [SELECT Id,Name,Artera_Region__r.Name, (SELECT Id,Name
                ,Type__c FROM Hydro_X_Job_Allocations__r WHERE Job_Assignment_Date_Field__c=:tomorrow)
                                                    FROM Artera_Resource__c
                                                    WHERE Worker_Status__c = 'Active' AND Job_Title__c LIKE 'CDL Operator%' ];
    
                for(Artera_Resource__c obj : resList ){
                    if(obj.Hydro_X_Job_Allocations__r.size()==0){
                        bgColor = 'slds-badge cus-font';title  = 'Available'; 
                    }else if(obj.Hydro_X_Job_Allocations__r.size()==1){
                        bgColor = 'slds-badge slds-theme_success';title  = 'Scheduled';
                    }else if(obj.Hydro_X_Job_Allocations__r.size()>=2){
                        bgColor = 'slds-badge slds-theme_error';title  = 'Scheduled';
                    } 
    
                    if(obj.Hydro_X_Job_Allocations__r.size() > 0){
    
                        for(Artera_Job_Allocation__c atAlloc : obj.Hydro_X_Job_Allocations__r){
                            if(atAlloc.Type__c=='Leave'){
                                bgColor = 'slds-badge slds-theme_error';
                                title  = 'Unavailable';
                            }
                        }
    
                    }
                    
                    resWrapper.add(new resWraCls(obj.Name, obj.Artera_Region__r.Name, title, bgColor));
                }
    
                if(!resWrapper.isEmpty()){
                    retString =  JSON.serialize(resWrapper);
                }
                return retString;
                
            } catch (Exception e) { throw new AuraHandledException(e.getMessage()); }
        }
    
        @AuraEnabled(cacheable = true)
        public static String getAllResourcesByFilters(String resource,Date fDate,  List<String> fRegion){
            try {
                List<resWraCls> resWrapper = new List<resWraCls>();
                Date today    = Date.today();
                Date tomorrow = today.addDays(1);    
                String bgColor;
                String title;
                String retString;
                String jobTitle = 'CDL Operator%';
                String jobTitleNon = 'Non-CDL%';
                String filter = '%' + resource + '%';   
                String status = 'Active';   
                List<Artera_Resource__c> extQuery; 
                
                system.debug('Res '+resource+' date '+fDate+' Region '+fRegion );
    
                String fetchQuery = 'SELECT Id,Name,Artera_Region__r.Name, (SELECT Id,Name,Type__c FROM Hydro_X_Job_Allocations__r ';
    
                if(fDate!= null ){
                    fetchQuery +=' WHERE Job_Assignment_Date_Field__c=:fDate) ';
                }else{
                    fetchQuery +=' WHERE Job_Assignment_Date_Field__c=:tomorrow) ';
                }   
    
                //fetchQuery += ' FROM Artera_Resource__c WHERE Worker_Status__c =:status AND (Job_Title__c LIKE :jobTitle OR Job_Title__c LIKE :jobTitleNon)';
                fetchQuery += ' FROM Artera_Resource__c WHERE Worker_Status__c =:status AND Job_Title__c LIKE :jobTitle ';
    
                if(!fRegion.isEmpty()){
                    fetchQuery += ' AND Artera_Region__c IN : fRegion ';
                }
    
                if(resource != null){
                    fetchQuery += ' AND Name LIKE :filter ';
                }
     
                system.debug('queryy '+fetchQuery);
                // if(String.isNotBlank(resource)){
                //         extQuery = [SELECT Id,Name,Artera_Region__r.Name, (SELECT Id,Name,Type__c FROM Hydro_X_Job_Allocations__r WHERE Job_Assignment_Date_Field__c=:tomorrow) FROM Artera_Resource__c WHERE  Name LIKE :filter AND Worker_Status__c = 'Active'];
                //     }else{
                //         extQuery = [SELECT Id,Name,Artera_Region__r.Name, (SELECT Id,Name,Type__c FROM Hydro_X_Job_Allocations__r WHERE Job_Assignment_Date_Field__c=:tomorrow) FROM Artera_Resource__c WHERE Worker_Status__c = 'Active'];
                //     }
                for(Artera_Resource__c obj : Database.query(fetchQuery) ){
                    if(obj.Hydro_X_Job_Allocations__r.size()==0){
                        bgColor = 'slds-badge cus-font'; title  = 'Available';
                    }else if(obj.Hydro_X_Job_Allocations__r.size()==1){
                        bgColor = 'slds-badge slds-theme_success'; title  = 'Scheduled';
                    }else if(obj.Hydro_X_Job_Allocations__r.size()>=2){
                        bgColor = 'slds-badge slds-theme_error';
                        title  = 'Scheduled';
                    } 
    
                    if(obj.Hydro_X_Job_Allocations__r.size() > 0){
    
                        for(Artera_Job_Allocation__c atAlloc : obj.Hydro_X_Job_Allocations__r){
                            if(atAlloc.Type__c=='Leave'){
                                bgColor = 'slds-badge slds-theme_error';title  = 'Unavailable';
                            }
                        }
    
                    }
    
    
                    resWrapper.add(new resWraCls(obj.Name, obj.Artera_Region__r.Name, title, bgColor));
                }
    
                if(!resWrapper.isEmpty()){
                    retString =  JSON.serialize(resWrapper);
                }
                 
                
                return retString;
                
            } catch (Exception e) { throw new AuraHandledException(e.getMessage());
            }
        }
    
    
        public class resWraCls{ 
            public String Name;
            public String Region;
            public String Title;
            public String BgColor; 
    
            public resWraCls(String Name, String Region, String Title, String BgColor){
            
                this.Name = Name;
                this.Region = Region;
                this.Title = Title;
                this.BgColor = BgColor;    
                    
            }
        }
        
    }