objects/Artera_Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Job Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Assignment in Progress</fullName>
                </value>
                <value>
                    <fullName>Dispatched</fullName>
                </value>
                <value>
                    <fullName>Dispatched - Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Pending Supervisor Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Admin Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Billing Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Payroll Approval</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/dispatchJobsHandler.cls
public class dispatchJobsHandler {
    public static void onStatusChange(List<Artera_Job__c> jobList, Map<Id, Artera_Job__c> oldjobList){              
           
                List<string> JobIds = new List<String>();
        system.debug(joblist);
      
        for(Artera_Job__c j : jobList){  
            Artera_Job__c oldJobs = oldjobList.get(j.ID);
                if(j.Status__c == 'Dispatched' && oldJobs.Status__c == 'Assignment in Progress') {   
                      System.debug('kamil');
                    JobIds.add(j.Id);
                
                          
            }
        }
        if(JobIds != null){
             System.debug('kamil');
        DispatchJobsInBulk.DispatchJob(jobIds);
        }
        }
}