objects/Artera_Region__c.object
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Artera Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Region</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Artera_Resource__c.object
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Hydro_X_Resources1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Artera_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Artera Region</label>
        <referenceTo>Artera_Region__c</referenceTo>
        <relationshipName>Artera_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supervisor_Name__c</fullName>
        <label>Supervisor ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_WorkLocation__c</fullName>
        <label>Home WorkLocation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

classes/UpdateResource.cls
global class UpdateResource implements Schedulable {
    global void execute(SchedulableContext sc){
        List<Artera_Resource__c> SobjLst = [select id,Home_WorkLocation__c,Artera_Region__c,Supervisor_Name__c from Artera_Resource__c ];
        List<Artera_Region__c> prodLst = [SELECT ID, Name FROM Artera_Region__c];
        List<User> UserLst = [SELECT ID,EmployeeNumber FROM User];
        Map<String,Id> discCode = new Map<String,Id>();
        Map<String,Id> UserCode = new Map<String,Id>();
        
        
        
        for (Artera_Region__c Ar: prodLst) {
            discCode.put(Ar.Name,Ar.Id);
        }
        for (User Us: UserLst) {
            UserCode.put(Us.EmployeeNumber,Us.Id);
        }
        
        
        
        
        for (Artera_Resource__c obj: SobjLst){
            obj.Artera_Region__c=discCode.get(obj.Home_WorkLocation__c);
            obj.Supervisor__c=UserCode.get(obj.Supervisor_Name__c);    
            
        }
        System.debug('Resource' +SobjLst);
        Update SobjLst;
        
    }
}