objects/Artera_Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Job Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Assignment in Progress</fullName>
                </value>
                <value>
                    <fullName>Dispatched</fullName>
                </value>
                <value>
                    <fullName>Dispatched - Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Pending Supervisor Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Admin Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Billing Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Payroll Approval</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Artera_Job_Allocation__c.object
<CustomObject>
    <label>Job Assignment</label>
    <nameField>
        <displayFormat>JAN-{0000}</displayFormat>
        <label>Job Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Artera_Job__c</referenceTo>
        <relationshipName>Job_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unassigned</fullName>
                    <default>true</default>
                    <label>Unassigned</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                    <isActive>false</isActive>
                    <label>Declined</label>
                </value>
                <value>
                    <fullName>Dispatch</fullName>
                    <isActive>false</isActive>
                    <label>Dispatch</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/UpdateJobAllocationStatus.cls
/**
 @author Kamil 
 @date 17/03/2022
 @group Artera_Job__c
 @description Apex Email handler class for handling inbound email messages from resource/ Operators for acknowledging the jobs 
 they have been assigned
 Name : UpdateJobAllocationStatus .
 @lastModifiedOn 09/04/2022 
 @lastModifiedBy Kamil
*/

public with sharing class  UpdateJobAllocationStatus implements  Messaging.InboundEmailHandler  {


    public static  Messaging.InboundEmailResult handleInboundEmail(Messaging.inboundEmail email, 
                                    Messaging.InboundEnvelope env){

                                        
                                        
    Messaging.InboundEmailResult result = new Messaging.InboundEmailResult();


    string myPlainText = email.plainTextBody;
    string content = email.subject ;
    
    System.debug('###########' + content  + '#######');   
    System.debug('###########' + email.subject + '###########'); 

    List<string> jnames =  content.split(' ');
    string jnumber = jnames[1];
    System.debug('##### ' + jnumber + '####');

    Artera_Job_Allocation__c obj = [SELECT ID ,Job__c, Name , Status__c FROM Artera_Job_Allocation__c  WHERE name  =: jnumber  LIMIT 1];
    obj.Status__c = 'Acknowledged' ;  

    update obj;

    Id RelatedJob =  obj.Job__c ;
   
   
    Artera_Job__c Artjob  = new Artera_Job__c ();
    ArtJob = [SELECT Id ,Status__c, Name ,(SELECT ID,Name , Status__c FROM Job_Allocations__r) FROM Artera_Job__c WHERE ID =: RelatedJob LIMIT 1];

    system.debug('Related Job :' +ArtJob);
    Boolean flag = true ;
   
     for(Artera_Job_Allocation__c JobAlloc : ArtJob.Job_Allocations__r )
     {
        
         if( JobAlloc.status__c != 'Acknowledged')
         {
             flag = false; 

         }
     }
     
     if(flag == true )
     {
         ArtJob.Status__c = 'Dispatched - Acknowledged' ;
     }
     update ArtJob ;

    
                                
    result.success = true;

    return result;                                                       
                                    
    }
    }