objects/Artera_Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project__c.Status__c</field>
                <operation>equals</operation>
                <value>A</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Date__c</fullName>
        <label>Job Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Job_Location__c</fullName>
        <label>Job Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Customer_Job_No__c</fullName>
        <label>Customer Job No.</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Description__c</fullName>
        <label>Job Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>created_by_using_multi_Job_creation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>created by using multi Job creation</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WeekDaysActionTestClass.cls
@isTest
public class WeekDaysActionTestClass {
    @isTest
    public static void testMethod1()
    {        
       List<Artera_Job__c> jobList=new List<Artera_Job__c>();
            Artera_Job__c  job = new Artera_Job__c (
                    Job_Date__c = date.ValueOf('2022-09-21'),
                    Project__c = 'a1i8Z000006N8nvQAC',
                    Contact__c = '0038Z00002qR43NQAS',
                    Job_Location__c = 'US',
                    Job_Description__c = 'Description',
                    Customer_Job_No__c = '986577',
            created_by_using_multi_Job_creation__c = True);
        //jobList.add(aJob);
        system.debug(jobList);
        insert job;
        test.startTest();
               WeekDaysActionClass.WeekDaysActionClasswrapper pp=new WeekDaysActionClass.WeekDaysActionClasswrapper();

        List<WeekDaysActionClass.WeekDaysActionClasswrapper> pp1=new List<WeekDaysActionClass.WeekDaysActionClasswrapper>();
         pp.strtDate=date.ValueOf('2022-09-21');
         pp.Projects= 'a1i8Z000006N8nvQAC';
         pp.enddate=date.ValueOf('2022-09-22');
         pp.daysList='Monday;Tuesday';
         pp.Contacts='0038Z00002qR43NQAS';
         pp.Location='US';
         pp.Description= 'Description';
         pp.Customer_Job_Number='Description';
        pp1.add(pp);
           WeekDaysActionClass.calculateDayWeeks(pp1);  
        test.stopTest();
    }
     @isTest
     public static void testMethod2()
    {        
       List<Artera_Job__c> jobList=new List<Artera_Job__c>();
            Artera_Job__c  job = new Artera_Job__c (
                    Job_Date__c = date.ValueOf('2022-09-21'),
                    Project__c = 'a1i8Z000006N8nvQAC',
                    Contact__c = '0038Z00002qR43NQAS',
                    Job_Location__c = 'US',
                    Job_Description__c = 'Description',
                    Customer_Job_No__c = '986577',
                    created_by_using_multi_Job_creation__c = True);
        //jobList.add(aJob);
        system.debug(jobList);
        insert job;
        test.startTest();
               WeekDaysActionClass.WeekDaysActionClasswrapper pp=new WeekDaysActionClass.WeekDaysActionClasswrapper();

        List<WeekDaysActionClass.WeekDaysActionClasswrapper> pp1=new List<WeekDaysActionClass.WeekDaysActionClasswrapper>();
         pp.strtDate=date.ValueOf('2022-09-21');
         pp.Projects= 'a1i8Z000006N8nvQAC';
         pp.enddate=date.ValueOf('2022-09-22');
         pp.daysList='';
         pp.Contacts='0038Z00002qR43NQAS';
         pp.Location='US';
         pp.Description= 'Description';
         pp.Customer_Job_Number='Description';
        pp1.add(pp);
           WeekDaysActionClass.calculateDayWeeks(pp1);  
        test.stopTest();
    }
}