objects/Artera_Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Job_Location__c</fullName>
        <label>Job Location</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

objects/Artera_Job_Allocation__c.object
<CustomObject>
    <label>Job Assignment</label>
    <nameField>
        <displayFormat>JAN-{0000}</displayFormat>
        <label>Job Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Artera_Job__c</referenceTo>
        <relationshipName>Job_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <formula>Artera_Resource__r.Employee_ID__c</formula>
        <label>Employee ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Artera_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Artera_Resource__c.Worker_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Artera_Resource__c</referenceTo>
        <relationshipLabel>Job Assignments</relationshipLabel>
        <relationshipName>Hydro_X_Job_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Artera_Resource__c.object
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <externalId>true</externalId>
        <label>Employee ID</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Worker_Status__c</fullName>
        <label>Worker Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/SendingEmailUponJobCancellationTest.cls
@isTest
public class SendingEmailUponJobCancellationTest {
    
    @isTest
    public static void SendingEmailUponJobCancellationTest(){
       
        Artera_Resource__c Resource = new Artera_Resource__c();
    Resource.Name = 'New Resource test' ;
        Resource.Worker_Status__c = 'Active';
    Resource.Employee_ID__c ='83643434';
        Resource.Email__c= 'Kkamran336@gmail.com';
    insert Resource ;
        
        	Artera_Job__c TestJob = new Artera_Job__c ();
        //TestJob.Name = 	'ArteraJobTest' ;
        TestJob.Job_Location__c ='Birmingham';
        insert Testjob ;
        	
        Artera_Job_Allocation__c JobAssignmentTest = new Artera_Job_Allocation__c ();
        JobAssignmentTest.job__c = Testjob.Id ;
        JobAssignmentTest.Artera_Resource__c = Resource.Id ;
        Insert JobAssignmentTest ;
        
        List<Artera_Job_Allocation__c> ArteraJobAllocations = new List<Artera_Job_Allocation__c>();
        ArteraJobAllocations.add(JobAssignmentTest);
     
        
        Test.startTest() ;
        SendingEmailUponJobCancellation.InformResource(ArteraJobAllocations);
            Test.stopTest();
        
    }

}