objects/Artera_Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Job Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Assignment in Progress</fullName>
                </value>
                <value>
                    <fullName>Dispatched</fullName>
                </value>
                <value>
                    <fullName>Dispatched - Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Pending Supervisor Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Admin Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Billing Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Payroll Approval</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project__c.Status__c</field>
                <operation>equals</operation>
                <value>A</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Location__c</fullName>
        <label>Job Location</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

objects/Artera_Job_Allocation__c.object
<CustomObject>
    <label>Job Assignment</label>
    <nameField>
        <displayFormat>JAN-{0000}</displayFormat>
        <label>Job Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Artera_Job__c</referenceTo>
        <relationshipName>Job_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unassigned</fullName>
                    <default>true</default>
                    <label>Unassigned</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                    <isActive>false</isActive>
                    <label>Declined</label>
                </value>
                <value>
                    <fullName>Dispatch</fullName>
                    <isActive>false</isActive>
                    <label>Dispatch</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>Job__r.Project__r.Project_Id__c</formula>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <formula>Artera_Resource__r.Employee_ID__c</formula>
        <label>Employee ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Artera_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Artera_Resource__c.Worker_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Artera_Resource__c</referenceTo>
        <relationshipLabel>Job Assignments</relationshipLabel>
        <relationshipName>Hydro_X_Job_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Artera_Resource__c.object
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Hydro_X_Resources1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <externalId>true</externalId>
        <label>Employee ID</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Hydro_X_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/DispatchJobsInBulkTest.cls
@isTest
public class DispatchJobsInBulkTest {

    public static string JobAllocationId = '';
    public static string  JobId ='';
    public static string ResourceId = '';
    public static string ProjectId ='';
    public static string SupervisorId = '';
    public static string USerId = '';
    // public static string JobAllocationId1 = '';
    // public Static string  JobId1 ='';
    // Public Static string ResourceId1 = '';
    // Public static string ProjectId1 ='';
    // Public static string SupervisorId1 = '';
    //Public static string USerId1 = '';

    // new variable

    
    @TestSetup
    static void makeData(){
        
        UserRole r = new UserRole(DeveloperName = 'MyCustomRole' , Name = 'MyRole');
        insert r ;
        
        User u = new User(
            ProfileId=[SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            LastName = 'Kamran',
            Email = 'Kkamran336@gmail.com',
            MobilePhone = '8340277080',
            username = 'kk000@gmail.com' + System.currentTimeMillis(),
            CompanyName ='Artera',
            Title ='Associate Developer',
            Alias ='alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey ='en_US',
            LocaleSidKey = 'en_US',
            UserRoleId = r.Id
        ); 
        UserId = u.Id;
        insert u;
        
        
           UserRole r1 = new UserRole(DeveloperName = 'MyCustomRole1' , Name = 'MyRole1');
    insert r1 ;
    User sup = new User(
        ProfileId=[SELECT Id FROM Profile WHERE Name = 'Hydro-X Supervisor'].Id,
        LastName = 'Kamran Supervisor',
        Email = 'Kkamran336@gmail.com',
        MobilePhone = '8340277080',
        username = 'kk000@gmail.com' + System.currentTimeMillis(),
        CompanyName ='Artera',
        Title ='Associate Developer',
        Alias ='alias',
        TimeZoneSidKey = 'America/Los_Angeles',
        EmailEncodingKey = 'UTF-8',
        LanguageLocaleKey ='en_US',
        LocaleSidKey = 'en_US',
        UserRoleId = r1.Id
    );  
    insert sup;        
   
 }
    
    @isTest
    public static void SendSMSToSupervisorTest() {      
      
        User Myuser = [SELECT ID ,Name FROM user WHERE LastName = 'Kamran' LIMIT 1];
        

        Artera_Resource__c resource = new Artera_Resource__c();
        resource.Name = 'Tim';
        resource.Employee_ID__c = 'E1S50X2BA24';
        resource.Email__c= 'test@artera.com';
        resource.Supervisor__c = Myuser.Id;
        resource.Salesforce_User__c = Myuser.Id;
        
        insert resource;
        ResourceId =resource.Id;
        Project__c ProjectTest = new Project__c();
        ProjectTest.Name = 'Test Project company';
        ProjectTest.Status__c = 'A';
        
        insert ProjectTest ;
        ProjectId =ProjectTest.Id ;
        
        Artera_Job__c JobTest = new Artera_Job__c();
        JobTest.Job_Location__c ='Birmingham' ;
        insert JobTest ;
        JobId=JobTest.Id;
        
        Artera_Job_Allocation__c JobAllocationTest = new Artera_Job_Allocation__c();
        JobAllocationTest.Job__c = JobTest.Id ;
        JobAllocationTest.Artera_Resource__c = resource.Id;
        
        insert JobAllocationTest;
        JobAllocationId = JobAllocationTest.Id ;


        Artera_Job_Allocation__c JobAlloc = [SELECT ID, Name ,Artera_Resource__c,Artera_Resource__r.Phone_Number__c,Artera_Resource__r.Supervisor__c,Artera_Resource__r.Supervisor__r.MobilePhone ,Status__c FROM Artera_Job_Allocation__c WHERE Id =: JobAllocationId] ;
        Test.startTest();
        DispatchJobsinBulk.SendSMSToSupervisor(JobAlloc);
        Test.stopTest();
    }

@isTest
public static void SendSMSToOperatotWithNotes()
{

    User Myuser = [SELECT ID ,Name FROM user WHERE LastName = 'Kamran' LIMIT 1];
        

    Artera_Resource__c resource = new Artera_Resource__c();
    resource.Name = 'Tim';
    resource.Employee_ID__c = 'E1S50X2BA23';
    resource.Email__c= 'test@artera.com';
    resource.Supervisor__c = Myuser.Id;
    resource.Salesforce_User__c = Myuser.Id;
    
    insert resource;
    ResourceId =resource.Id;
    Project__c ProjectTest = new Project__c();
    ProjectTest.Name = 'Test Project company';
    ProjectTest.Status__c = 'A';
    
    insert ProjectTest ;
    ProjectId =ProjectTest.Id ;
    
    Artera_Job__c JobTest = new Artera_Job__c();
    JobTest.Job_Location__c ='Birmingham' ;
     insert JobTest ;
     JobId=JobTest.Id;
    
    Artera_Job_Allocation__c JobAllocationTest = new Artera_Job_Allocation__c();
    JobAllocationTest.Job__c = JobTest.Id ;
    JobAllocationTest.Artera_Resource__c = resource.Id;
    
    insert JobAllocationTest;
    JobAllocationId = JobAllocationTest.Id ;

    Artera_Job_Allocation__c JobAlloc = [SELECT ID, Name ,Artera_Resource__c,Artera_Resource__r.Phone_Number__c,Artera_Resource__r.Supervisor__c,Artera_Resource__r.Supervisor__r.MobilePhone ,Status__c FROM Artera_Job_Allocation__c WHERE Id =: JobAllocationId] ;

    Test.startTest();
        DispatchJobsinBulk.SendSMSToOperatorWithNotes(JobAlloc);
        Test.stopTest();

}

@isTest  
public static void SendSMSToOperatorWithoutNotes()
{

    User Myuser = [SELECT ID ,Name FROM user WHERE LastName = 'Kamran' LIMIT 1];
        

    Artera_Resource__c resource = new Artera_Resource__c();
    resource.Name = 'Tim';
    resource.Employee_ID__c = 'E1S50X2BA23';
    resource.Email__c= 'test@artera.com';
    resource.Supervisor__c = Myuser.Id;
    resource.Salesforce_User__c = Myuser.Id;
    
    insert resource;
    ResourceId =resource.Id;
    Project__c ProjectTest = new Project__c();
    ProjectTest.Name = 'Test Project company';
    ProjectTest.Status__c = 'A';
    
    insert ProjectTest ;
    ProjectId =ProjectTest.Id ;
    
    Artera_Job__c JobTest = new Artera_Job__c();
    JobTest.Job_Location__c ='Birmingham' ;
     insert JobTest ;
     JobId=JobTest.Id;
    
    Artera_Job_Allocation__c JobAllocationTest = new Artera_Job_Allocation__c();
    JobAllocationTest.Job__c = JobTest.Id ;
    JobAllocationTest.Artera_Resource__c = resource.Id;
    
    insert JobAllocationTest;
    JobAllocationId = JobAllocationTest.Id ;

    Artera_Job_Allocation__c JobAlloc = [SELECT ID, Name ,Artera_Resource__c,Artera_Resource__r.Phone_Number__c,Artera_Resource__r.Supervisor__c,Artera_Resource__r.Supervisor__r.MobilePhone ,Status__c FROM Artera_Job_Allocation__c WHERE Id =: JobAllocationId] ;

    Test.startTest();
        DispatchJobsinBulk.SendSMSToOperatorWithoutNotes(JobAlloc);
    Test.stopTest();
}

@isTest
public static void SendCustomNotificationTest()
{

    User Myuser = [SELECT ID ,Name FROM user WHERE LastName = 'Kamran' LIMIT 1];
        

    Artera_Resource__c resource = new Artera_Resource__c();
    resource.Name = 'Tim';
    resource.Employee_ID__c = 'E1S50X2BA23';
    resource.Email__c= 'test@artera.com';
    resource.Supervisor__c = Myuser.Id;
    resource.Salesforce_User__c = Myuser.Id;
    
    insert resource;
    ResourceId =resource.Id;
    Project__c ProjectTest = new Project__c();
    ProjectTest.Name = 'Test Project company';
    ProjectTest.Status__c = 'A';
    
    insert ProjectTest ;
    ProjectId =ProjectTest.Id ;
    
    Artera_Job__c JobTest = new Artera_Job__c();
    JobTest.Job_Location__c ='Birmingham' ;
     insert JobTest ;
     JobId=JobTest.Id;
    
    Artera_Job_Allocation__c JobAllocationTest = new Artera_Job_Allocation__c();
    JobAllocationTest.Job__c = JobTest.Id ;
    JobAllocationTest.Artera_Resource__c = resource.Id;
    
    insert JobAllocationTest;
    JobAllocationId = JobAllocationTest.Id ;

    Artera_Job_Allocation__c JobAlloc = [SELECT ID, Name ,Artera_Resource__c,Artera_Resource__r.Phone_Number__c,
                                         Artera_Resource__r.Supervisor__c,Artera_Resource__r.Salesforce_User__c,
                                         Artera_Resource__r.Supervisor__r.MobilePhone ,Job__r.Project__c,
                                         Job__r.Name,
                                         Status__c FROM Artera_Job_Allocation__c WHERE Id =: JobAllocationId] ;

    Test.startTest();
        DispatchJobsinBulk.SendCustomNotification(JobAlloc);
    Test.stopTest();


}
    
     @isTest
     static  void testIncrement() {
         Test.startTest();
        DispatchJobsInBulk.justIncrement();
        Test.stopTest();
     }


}