objects/Artera_Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Job Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Assignment in Progress</fullName>
                </value>
                <value>
                    <fullName>Dispatched</fullName>
                </value>
                <value>
                    <fullName>Dispatched - Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Pending Supervisor Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Admin Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Billing Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Payroll Approval</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job_Location__c</fullName>
        <label>Job Location</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

objects/Artera_Job_Allocation__c.object
<CustomObject>
    <label>Job Assignment</label>
    <nameField>
        <displayFormat>JAN-{0000}</displayFormat>
        <label>Job Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Artera_Job__c</referenceTo>
        <relationshipName>Job_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unassigned</fullName>
                    <default>true</default>
                    <label>Unassigned</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                    <isActive>false</isActive>
                    <label>Declined</label>
                </value>
                <value>
                    <fullName>Dispatch</fullName>
                    <isActive>false</isActive>
                    <label>Dispatch</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Artera_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Artera_Resource__c.Worker_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Artera_Resource__c</referenceTo>
        <relationshipLabel>Job Assignments</relationshipLabel>
        <relationshipName>Hydro_X_Job_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Artera_Resource__c.object
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
</CustomObject>

classes/JobStatusCancelledHandlerTest.cls
@isTest

public class JobStatusCancelledHandlerTest {
    public static string JobAllocationId = '';
    public static string  JobId ='';
    public static string ResourceId = '';
    @isTest static void onStatusChangeTest(){
        
        Artera_Job__c JobTest1 = new Artera_Job__c();
        JobTest1.Job_Location__c ='Birmingham' ;
        JobTest1.Status__c = 'Cancelled';
        insert JobTest1 ;
        JobId=JobTest1.Id;
              
        Artera_Job_Allocation__c JobAllocationTest = new Artera_Job_Allocation__c();
        JobAllocationTest.Job__c = JobTest1.Id ;
        System.debug('res '+JobAllocationTest.Artera_Resource__c);
        insert JobAllocationTest;
        JobAllocationId = JobAllocationTest.Id ;
        
        
        Artera_Job_Allocation__c JobAlloc = [SELECT ID, Name ,Artera_Resource__c,Artera_Resource__r.Phone_Number__c,
                                             Artera_Resource__r.Email__c,Status__c FROM Artera_Job_Allocation__c WHERE Id =: JobAllocationId] ;
        
       
        
        
        Map<Id, Artera_Job__c> oldJob = new  Map<Id, Artera_Job__c>();
        JobTest1.Job_Location__c ='Birmingham' ;
        System.debug('JobAllocationTest.Job__r.Id ' + JobAllocationTest.Job__c);
        JobTest1.Status__c = 'Dispatched';       
        oldJob.put(JobAllocationTest.Job__c , JobTest1);
        
      
         Artera_Job__c JobTest2 = new Artera_Job__c();
        JobTest2.Job_Location__c ='NYC' ;
        JobTest2.Status__c = 'Dispatched';
        insert JobTest2 ;
        JobId=JobTest2.Id;
        
         List<Artera_Job__c> JobTest3 = new List<Artera_Job__c>();
        JobTest2.Status__c = 'Cancelled';
        JobTest3.add(JobTest2);
        
        Test.startTest();
        List <Artera_job__c> newJobList = new List <Artera_job__c>();
        newJobList.add(JobTest1);
        update JobTest3;
        JobStatusCancelledHandler.onStatusChange(newJobList, oldJob);
        //update oldJob;
        Test.stopTest();          
    }
    
    
    @isTest
    public static void SendSMSToOperatotWithNotes()
    {
        
        Artera_Job__c JobTest = new Artera_Job__c();
        JobTest.Job_Location__c ='Birmingham' ;
        JobTest.Status__c = 'Cancelled';
        insert JobTest ;
        JobId=JobTest.Id;
        
        Artera_Job_Allocation__c JobAllocationTest = new Artera_Job_Allocation__c();
        JobAllocationTest.Job__c = JobTest.Id ;
        insert JobAllocationTest;
        JobAllocationId = JobAllocationTest.Id ;
        
        Artera_Job_Allocation__c JobAlloc = [SELECT ID, Name ,Artera_Resource__c,Artera_Resource__r.Phone_Number__c,Artera_Resource__r.Email__c,Status__c FROM Artera_Job_Allocation__c WHERE Id =: JobAllocationId] ;
        
        Test.startTest();
        JobStatusCancelledHandler.SendSMSToOperatorWithNotes(JobAlloc);
        Test.stopTest();
        
    }
    
}