objects/Artera_Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Job_Date__c</fullName>
        <label>Job Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Owner_Name__c</fullName>
        <formula>Owner:User.FirstName&amp;&apos; &apos;&amp;Owner:User.LastName</formula>
        <label>Owner Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Location__c</fullName>
        <label>Job Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Dispatcher_Notes__c</fullName>
        <label>Dispatcher Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

objects/Artera_Job_Allocation__c.object
<CustomObject>
    <label>Job Assignment</label>
    <nameField>
        <displayFormat>JAN-{0000}</displayFormat>
        <label>Job Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Artera_Job__c</referenceTo>
        <relationshipName>Job_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Artera_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Artera_Resource__c.Worker_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Artera_Resource__c</referenceTo>
        <relationshipLabel>Job Assignments</relationshipLabel>
        <relationshipName>Hydro_X_Job_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Artera_Resource__c.object
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Hydro_X_Resources1</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

classes/SendingEmailUponJobCancellation.cls
/**
 @author Kamil 
 @date 22/04/2022
 @group Artera_Job__c
 @description Apex invocable class for sending mail to resource for Job being Cancelled being called by a running flow.
 they have been assigned
 Name :  SendingEmailUponJobCancellatiion.
 @lastModifiedOn 22/04/2022 
 @lastModifiedBy Kamil
*/

public class SendingEmailUponJobCancellation {
    @InvocableMethod(Label='Sending Email Through Resource' Description = 'Sending email through Resource')

    public static void InformResource(List<Artera_Job_Allocation__c> ArtJobAlloc) {

        
        string jobId = ArtJobAlloc[0].id ;
        List<string> toAddresses = new List<string>();
          
         

         Artera_Job_Allocation__c arteraJobAllocation = [SELECT Artera_Resource__r.Name, Artera_Resource__r.Email__c ,Job__r.Name, 
                                                         Job__r.Job_Date__c , Job__r.Supervisor__r.Name,
                                                 Job__r.Job_Location__c,Job__r.Dispatcher_Notes__c,Job__r.Owner_Name__c ,
                                                 Id,Name FROM Artera_Job_Allocation__c WHERE ID =: jobId];

        toAddresses.add(arteraJoballocation.Artera_Resource__r.Email__c);
        Map<string ,string> toSubject = new Map<string , string>();
           
        Map<string ,string> toBody = new Map<string, string>
        {
            'ResourceName' => arteraJobAllocation.Artera_Resource__r.Name ,
            'ArteraJobName'  => arteraJobAllocation.Job__r.Name ,
            'ArterajobDate'       => String.valueOf(arteraJobAllocation.Job__r.Job_Date__c) ,
            'LocationJob'   => arteraJobAllocation.Job__r.Job_Location__c ,
            'ArtJobId'        => arteraJobAllocation.Id,
            'JobOwner'   => arteraJobAllocation.Job__r.Owner_Name__c,
            'ArteraJobAllocationId' => arteraJobAllocation.Id ,
            'JobAssignmentName' => arteraJobAllocation.Name ,
            'ArteraSupervisorName ' => arteraJobAllocation.Job__r.Supervisor__r.Name
                
        };

        EmailUtilities.sendResultEmail('Job Cancelled' ,toAddresses ,toSubject,toBody );


    }

}