objects/Artera_Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Job_Date__c</fullName>
        <label>Job Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Job_Location__c</fullName>
        <label>Job Location</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

objects/Artera_Job_Allocation__c.object
<CustomObject>
    <label>Job Assignment</label>
    <nameField>
        <displayFormat>JAN-{0000}</displayFormat>
        <label>Job Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Artera_Job__c</referenceTo>
        <relationshipName>Job_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <formula>Artera_Resource__r.Employee_ID__c</formula>
        <label>Employee ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Artera_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Artera_Resource__c.Worker_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Artera_Resource__c</referenceTo>
        <relationshipLabel>Job Assignments</relationshipLabel>
        <relationshipName>Hydro_X_Job_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Artera_Resource__c.object
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <externalId>true</externalId>
        <label>Employee ID</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

objects/Job_Ticket__c.object
<CustomObject>
    <label>Job Ticket</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Job Ticket Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Job1__c</fullName>
        <label>Job</label>
        <referenceTo>Artera_Job__c</referenceTo>
        <relationshipLabel>Job Tickets</relationshipLabel>
        <relationshipName>Job_Tickets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/SendingEmailUponTicketCreation_Test.cls
@IsTest(SeeAllData=true)
public class SendingEmailUponTicketCreation_Test {
    
    @isTest
    static void sendemailnotifytest(){
        
        List<Artera_Job__c> ArtJob = new List<Artera_Job__c>();
        
        Artera_Resource__c resource = new Artera_Resource__c();
                resource.Name = 'Test Resource';
                resource.Employee_ID__c = 'Emp-22451678';
                resource.Email__c = 'simran.vyas@bugendaitech.com';
                insert resource;
        
        Artera_Job__c jobrec= new Artera_Job__c();
                jobrec.Job_Date__c= Date.today();
                jobrec.Job_Location__c = 'NYC Testing Job'; 
                insert jobrec;     
                     
        Artera_Job_Allocation__c jobAllocation = new Artera_Job_Allocation__c();
                jobAllocation.Artera_Resource__c = resource.Id;
                jobAllocation.Job__c = jobrec.Id;
                insert  jobAllocation; 
         
        List<Job_Ticket__c> jobTktList = new List<Job_Ticket__c>();
                for(Integer i=1; i<5 ; i++){
                    Job_Ticket__c jobTktObj = new Job_Ticket__c();
                    jobTktObj.Location__c = 'Location '+i;
                    jobTktObj.job1__c = jobrec.Id;
                    jobTktList.add(jobTktObj);
                }
                insert jobTktList;
        
        ArtJob.add(jobrec);
         
        Test.startTest();
        SendingEmailUponTicketCreation.SendingEmailToResources(ArtJob);      
        Test.stopTest(); 
        
    }
    
}