objects/Artera_Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project__c.Status__c</field>
                <operation>equals</operation>
                <value>A</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Date__c</fullName>
        <label>Job Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Job_Location__c</fullName>
        <label>Job Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Customer_Job_No__c</fullName>
        <label>Customer Job No.</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Description__c</fullName>
        <label>Job Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>created_by_using_multi_Job_creation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>created by using multi Job creation</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WeekDaysActionClass.cls
public class WeekDaysActionClass {
    @InvocableMethod(label = 'DaysWeek Calculation')
    public static void calculateDayWeeks(List<WeekDaysActionClasswrapper> param) {
        Date strtDate = param[0].strtdate;
        Date endDate = param[0].enddate;
        String daysList = param[0].daysList;
        String Contacts = param[0].Contacts;
        String Projects  = param[0].Projects;
        String Location = param[0].Location;
        String Description = param[0].Description;
        String Customer_Job_Number = param[0].Customer_Job_Number;
        String StartTime = param[0].StartTime;

        List<Artera_Job__c> jobList = new List<Artera_Job__c>();
        Artera_Job__c aJob;

        List<String> daylst = new List<String>();

        if(daysList != null){
            daylst = daysList.split(';'); 
            // System.debug('day'+daylst);
        }

        System.debug('startdate:: ' + strtDate);
        System.debug('enddate:: ' + endDate);
        System.debug('dayList:: ' + daylst);
      String[] strTimeSplit = StartTime.split(':');
  Time timeChange = Time.newInstance( Integer.valueOf(strTimeSplit[0]) //hour
                                     ,Integer.valueOf(strTimeSplit[1]) //min
                                     ,0                                //sec
                                     ,0);                              //ms
        Date sdt = strtDate;
        DateTime dayDate = (DateTime)sdt;
        
        System.debug('outside loop dayDate :: ' + dayDate);
       
        String day;
        Boolean isTrue = false;

        // String timezone  = String.valueof(UserInfo.getTimeZone().getID());
        System.debug('dayDate::'+dayDate);
        // dayDate = dayDate.addDays(1);

        while(dayDate <= endDate){

            system.debug('in loop daysList::' + daysList);

            if(daysList != null && String.isNotEmpty(daysList)){   
                system.debug('date :: ' + dayDate);
                
                day = dayDate.formatGmt('EEEE');
                System.debug('day::'+day);
                System.debug('day Lists::'+daylst);
                // Boolean dayContain = daylst.contains(day);
                //System.debug('dayContain:'+dayContain);
                if(daylst.contains(day)){
                    isTrue = true;
                    system.debug('isTrue: ' + istrue);
                }
            } else{
                isTrue = true;
                system.debug('date :: ' + dayDate);                
                system.debug('if False then isTrue: ' + istrue);
                
            }
            // dateForLoop + 1day
            if(isTrue){
                System.debug('dayDate.date() :: ' + dayDate.dateGmt());
                aJob = new Artera_Job__c (
                    Job_Date__c = dayDate.dateGmt(),
                    Project__c = Projects,
                    Contact__c = Contacts,
                    Job_Location__c = Location,
                    Job_Description__c = Description,
                    Customer_Job_No__c = Customer_Job_Number,
                    created_by_using_multi_Job_creation__c = True,
             	    Start_Date__c = timeChange
   );

                jobList.add(aJob);
                system.debug('List Of Jobs'+jobList);
            }
            
            isTrue = false;
            aJob = null;
            // dateForLoop = dateForLoop.addDays(1);
            dayDate = dayDate.addDays(1);
            system.debug('dayDate + 1 :: '+dayDate);
            // dateForStrt = dateForStrt.addDays(1);
        }
        system.debug('List Of Jobs'+jobList);
        
        try{
            Database.insert(jobList,false);
        }catch(DMLException e){
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
        
    }
    public class WeekDaysActionClasswrapper{
        @InvocableVariable(required = true)
        public Date strtDate;
        @InvocableVariable(required = true)
        public Date endDate;
        @InvocableVariable
        public String daysList;
        @InvocableVariable
        public String Contacts;
        @InvocableVariable(required = true)
        public String Projects;
        @InvocableVariable(required = true)
        public String Location;
        @InvocableVariable
        public String Description;
        @InvocableVariable
        public String Customer_Job_Number;
         @InvocableVariable
        public String StartTime;
    }
}