objects/Artera_Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Date__c</fullName>
        <label>Job Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Artera_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Area</label>
        <referenceTo>Artera_Region__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Hydro_X_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Artera_Region__c.object
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Artera Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Region</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset__c.object
<CustomObject>
    <label>Asset</label>
    <nameField>
        <label>Asset ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>Artera_Region__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

classes/TruckAvailabiltyCtrl.cls
public with sharing class TruckAvailabiltyCtrl {

    @AuraEnabled(cacheable = true)
    public static List<Artera_Region__c> getRegionList(){
        try {
            List<Artera_Region__c> region = new List <Artera_Region__c> ();
            region = [select Id, Name from Artera_Region__c ];
            region.sort();
            return region;
        } catch (Exception e) { throw new AuraHandledException(e.getMessage()); }
    }


    @AuraEnabled(cacheable = true)
    public static String getAllAsset(){
        try {
            List<resWraCls> resWrapper = new List<resWraCls>();
            Date today    = Date.today();
            Date tomorrow = today.addDays(1);     
            String bgColor;
            String title;
            String retString;
            List<Asset__c> resList = [SELECT Id,Name,Region__r.Name,(SELECT Id,Name FROM Jobs__r WHERE Job_Date__c=:tomorrow) FROM Asset__c];

            for(Asset__c obj : resList ){

                if(obj.Jobs__r.size()==0){
                    bgColor = 'slds-badge cus-font';title  = 'Available'; 
                }else if(obj.Jobs__r.size()>0 &&  obj.Jobs__r.size()<2){
                    bgColor = 'slds-badge slds-theme_success';title  = 'Scheduled';
                }else if(obj.Jobs__r.size()>=2){
                    bgColor = 'slds-badge slds-theme_error';title  = 'Scheduled';
                } 
                resWrapper.add(new resWraCls(obj.Name, obj.Region__r.Name, title, bgColor));
            }

            if(!resWrapper.isEmpty()){
                retString =  JSON.serialize(resWrapper);
            }
            return retString;
            
        } catch (Exception e) { throw new AuraHandledException(e.getMessage()); }
    }

    @AuraEnabled(cacheable = true)
    public static String getAllAssetsByFilters(String resource,Date fDate,List<String> fRegion){
        try {
            List<resWraCls> resWrapper = new List<resWraCls>();
            Date today    = Date.today();
            Date tomorrow = today.addDays(1);   
            String bgColor;
            String title;
            String retString;
            String filter = '%' + resource + '%';   
            List<Asset__c> extQuery;             
            String fetchQuery = 'SELECT Id,Name,Region__r.Name, (SELECT Id,Name FROM Jobs__r ';

            if(fDate!= null){
                fetchQuery +=' WHERE Job_Date__c=:fDate) ';
            }else{
                fetchQuery +=' WHERE Job_Date__c=:tomorrow) ';
            }   

            fetchQuery += ' FROM Asset__c  ';

            if(resource != null || !fRegion.isEmpty()){
                fetchQuery += ' WHERE ';
            }

            if(resource != null){
                fetchQuery += ' Name LIKE :filter ';
            }

            if(!fRegion.isEmpty()){
                if(resource == null){
                    fetchQuery += ' Region__c IN : fRegion  ';
                }else{
                    fetchQuery += ' AND Region__c IN : fRegion  ';
                }
                
            }

 
            system.debug('queryy '+fetchQuery);
            
            for(Asset__c obj : Database.query(fetchQuery) ){
                if(obj.Jobs__r.size()==0){
                    bgColor = 'slds-badge cus-font'; title  = 'Available';
                }else if(obj.Jobs__r.size()==1){
                    bgColor = 'slds-badge slds-theme_success'; title  = 'Scheduled';
                }else if(obj.Jobs__r.size()>=2){
                    bgColor = 'slds-badge slds-theme_error';
                    title  = 'Scheduled';
                } 
                resWrapper.add(new resWraCls(obj.Name, obj.Region__r.Name, title, bgColor));
            }

            if(!resWrapper.isEmpty()){
                retString =  JSON.serialize(resWrapper);
            }
             
            
            return retString;
            
        } catch (Exception e) { throw new AuraHandledException(e.getMessage());
        }
    }
 
    
    public class resWraCls{ 
        public String Name;
        public String Region;
        public String Title;
        public String BgColor; 

        public resWraCls(String Name, String Region, String Title, String BgColor){
        
            this.Name = Name;
            this.Region = Region;
            this.Title = Title;
            this.BgColor = BgColor;    
                
        }
    }
}