objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Project_Item__c.object
<CustomObject>
    <label>Project Item</label>
    <nameField>
        <label>Project Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <formula>Text(Item__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Items</relationshipLabel>
        <relationshipName>Project_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

classes/LineItemPicklistCtrl.cls
public with sharing class LineItemPicklistCtrl {
    public LineItemPicklistCtrl() {

    }

    @AuraEnabled(cacheable = true)
    public static List<Project_Item__c> getLineItemsList(String recordId){ 
        try { 
            List<Project_Item__c> lineItemList = new List <Project_Item__c> ();
                lineItemList = [SELECT Id, Name FROM Project_Item__c WHERE Project__c=:recordId AND Status__c = 'AC'];
            return lineItemList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}