objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Item__c.object
<CustomObject>
    <label>Project Item</label>
    <nameField>
        <label>Project Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>Unit_Item__c</referenceTo>
        <relationshipLabel>Project Items</relationshipLabel>
        <relationshipName>Project_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Items</relationshipLabel>
        <relationshipName>Project_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

objects/Unit_Item__c.object
<CustomObject>
    <label>Unit Item</label>
    <nameField>
        <label>Unit Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LineItemPicklistCtrlTest.cls
@isTest
public class LineItemPicklistCtrlTest {
    
    @isTest
	public static void LineItemPicklistCtrlTest()
    {
      LineItemPicklistCtrl NewCtrl = new LineItemPicklistCtrl();
        
    }

    @isTest
    public static void getLineItemsListTest() {

        Unit_Item__c NewUnitItem = new Unit_Item__c ();
        NewUnitItem.Name ='product' ;
        insert NewUnitItem;
        Project__c Newproject = new Project__c ();
        NewProject.Name = 'MyProject';
        insert Newproject ;


        Project_Item__c NewProjectItem = new Project_Item__c();
        NewProjectItem.Name = 'MyProjectItem' ;
        NewProjectItem.Project__c = Newproject.ID ;
        NewProjectItem.Item__c = NewUnitItem.ID;
        Insert NewProjectItem ;
        string recordId = NewProject.Id;
        Test.startTest();
        LineItemPicklistCtrl.getLineItemsList(recordId);
        Test.stopTest();
    }
}